### ISSUE TITLE
chain parameter in saveToRepo function

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#101]
Since we have `%a%` function in `archivist` package it looks like `chain` parameter is no longer needed in our package. Maybe we should change it's name to `value`, because it forces `saveToRepo()` to return archived artifact as a value of this function. We can add  `chain` to the `deprecated` information.  What do you think about that?

**Comment by pbiecek** [comment]
Good idea

**Comment by MarcinKosinski** [comment]
done with https://github.com/pbiecek/archivist/commit/b6f1c7721ff9579245fb9d0d3b216555594d1c25
