### ISSUE TITLE
Default values of the saveToRepo function

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#102]
By now the `saveToRepo` function is declared as:

````{R}
saveToRepo <- function( artifact, repoDir = NULL, archiveData = TRUE, 
                        archiveTags = TRUE, 
                        archiveMiniature = TRUE, force = TRUE, rememberName = TRUE, 
                        chain = FALSE, ... , userTags = c(), 
                        silent=aoptions("silent"), ascii = FALSE, format = aoptions("format"))
````

The `silent` parameter uses global-archivist objects - other parameters does not use those options. When repoDir is set to NULL it uses global options that are checked inside function. It is not so elegant and consistent.

My proposition is to set all parameters to global-archivist options, and set those options during the package load (`zzz.R` file). We could also add an information in `saveToRepo` function that options can be changed in `aoptions` function and give a link to this function. The global-options at start should be set to the same values as they are now in `saveToRepo` function. What do you think about that?

**Comment by pbiecek** [comment]
Consistency is important.
but then, one may expect that aoptions is used for all parameters

**Comment by MarcinKosinski** [comment]
So let's go 1 step forward. Let's change it in all functions for all
parameters?

2015-10-26 21:21 GMT+01:00 pbiecek <notifications@github.com>:

**Comment by pbiecek** [comment]
I see that aoptions() is used in new functions. Shall we close this issue?

**Comment by MarcinKosinski** [comment]
In nes yes. But not in all. By the way I am currently thinking about replacing saveTiRepo function with archive function 

Marcin Kosinski

Dnia 28 lis 2015 o godz. 20:27 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
archive() is a good name, but do not delete saveToRepo() to keep backward compatibility.
archive=saveToRepo should do the work

**Comment by MarcinKosinski** [comment]
I wasn't thinking about removing `saveToRepo` but about adding a `type = local/both/github` parameter to `archive`. By now I needed to copy the code from `saveToRepo` to the `archive` function since the code

````{R}
archive <- function(...){
    saveToRepo(...)
}
````
does not remember artifacts' names.

**Comment by pbiecek** [comment]
archive = saveToRepo
is better solution than
archive <- function(...){
    saveToRepo(...)
}

The latter creates additional function and a closure.
The first just create a copy

**Comment by wchodor** [comment]
After having repository object, default arguments will be set there.
