### ISSUE TITLE
Archivist.png update

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#103]
I think in some time we will need a new version of that file https://github.com/pbiecek/archivist/blob/master/archiwum.png - but let's wait for `archive`, `createEmptyGithubRepo`, `commitRepo/pushRepo` and `pin` functions

**Comment by MarcinKosinski** [comment]
I think this prototype explains archivist in broader way

![zdjecie2](https://cloud.githubusercontent.com/assets/6773454/10935880/4a978b26-82e9-11e5-9ae6-eddf22a0c389.JPG)

**Comment by MarcinKosinski** [comment]
@pbiecek @wchodor maybe we should have 2 different schemes visualizations? One for local functions and one for github? This might be easier to visualize the functionalities of archivist?

**Comment by pbiecek** [comment]
Whatever is easier to understand for the user. 
In the article we are using public/local names and these are separate usecases, so we may have two graphs.

**Comment by MarcinKosinski** [comment]
moved to #244
