### ISSUE TITLE
graphGallery Repository

### ISSUE THREAD

**Issue by wchodor** [pbiecek/archivist#118]
I'm wondering why there is so much copies of artifacts in backpack database in this Repository. There are 446 artifacts from which only 28 are unique ones. Is it made on purpose?

**Comment by pbiecek** [comment]
Every event, like creation / update of an artifact is recorded. So if someone adds 'iris' to the repository 100 times there should be 100 entries for it (with same hash).

**Comment by MarcinKosinski** [comment]
Do we want to have unique artifacts?

**Comment by pbiecek** [comment]
For search* function it might be useful to search by the date of creation. 
So somewhere in backpack.db we should have these dates.
In this table or in a separate table? I will vote for simpler structure of the database.
But we may discuss this on Friday.

**Comment by MarcinKosinski** [comment]
Yes but even when we will look at the date, the rows are non unique.

````R
> showLocalRepo( repoDir = archivistRepo ) %>% nrow
[1] 446
> showLocalRepo( repoDir = archivistRepo ) %>% unique %>% nrow
[1] 315
> showLocalRepo( repoDir = archivistRepo ) %>% select(md5hash, name) %>% unique %>% nrow
[1] 31
```

31 various artifacts, with 315 unique records and 131 copies of records

**Comment by MarcinKosinski** [comment]
Ok so If we do not remove duplicate rows, can we close this issue?
Or can one remove duplicated rows in this Repository and close this issue?
