### ISSUE TITLE
Change `tempdir()` function to `tempfile()` in all examples

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#124]

**Comment by wchodor** [comment]
It is not necessary to change `tempdir()` function to `tempfile` in all examples. It will be sufficient to change these examples in which in deleteRepo function there is deleteRoot=TRUE argument. We should simply call `deleteRepo(repoDir)` with deleteRoot=FALSE as default argument.

**Comment by MarcinKosinski** [comment]
Oh! Ok that's an idea.

**Comment by pbiecek** [comment]
deleteRoot=TRUE was added with intention to remove the directory with the repository.
Without that examples generate empty directories.

Could you show how to replicate the problem?

**Comment by pbiecek** [comment]
Ok, I see #125 
I guess that to replicate the way how repos are created we should create a directory in the tempdir()
either with tempfile() or with paste(tempdir(),"/repo")
Using tempdir() alone is risky because it is an existing directory (which I have not realised before)
The tempfile() will be a better solution (but then with force=TRUE).

**Comment by wchodor** [comment]
I agree with your point of view.
`createEmptyRepo` has `force=TRUE` argument as default so it's not necessary to use it  unless we want to emphasize this fact.
Anyway, I'm going to change `tempdir()` into `tempfile()`.

**Comment by wchodor** [comment]
```
createEmptyLocalRepo <- function( repoDir, force = TRUE, default = FALSE){
  stopifnot( is.character( repoDir ) )
  
  if ( !file.exists( repoDir ) & !force ) 
    stop( paste0("Directory ", repoDir, " does not exist. Try with force=TRUE.") )
```

**Comment by MarcinKosinski** [comment]
Were we really talking about `createEmpyRepo` or @pbiecek  you ment  `root=TRUE` for evaluating `deleteRepo` on `tempfile`?.

**Comment by pbiecek** [comment]
Sorry, I meant deleteRoot =TRUE in deleteRepo().
I assume that the repo dir is a separate folder only with repo related files. Of course we can discuss this assumption.

**Comment by MarcinKosinski** [comment]
@wchodor If this is done, can you close the issue?

I like the NOTE in `deleteRepo` about this issue 

> Remember that using tempfile() instead of tempdir() in examples section is crucial. tempdir() is existing directory in which R works so calling deleteRepo(exampleRepoDir, deleteRoot=TRUE) removes important R files. You can find out more information about this problem at stackoverflow webpage. - http://stackoverflow.com/questions/22325820/unlink-function-causing-an-error-for-consequent-and-plot-functions

Do we have this information in `NEWS.md`?

**Comment by wchodor** [comment]
We have an information explaining in which functions `tempfile()` replaced `tempdir()`
