### ISSUE TITLE
Spelling, documentation and examples check

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#136]
@wchodor  :) good we have you here

**Comment by MarcinKosinski** [comment]
@wchodor which documentation pages should we still check?

As far as am I concerned you are currently working on:
- `cache`
- `asearch`
- `ahistory`

I think there are those documentation pages left:
- `createEmptyGithubRepo` 
- `archive`
- `?agithub` - `githubFunctions.R` file

Do I miss something? 

By the way, can you edit my post :)?

**Comment by wchodor** [comment]
Perhaps `shinySearchInLocalRepo` should be checked as well? 

I  can not edit your post.

**Comment by MarcinKosinski** [comment]
@wchodor  Can you edit my post and cross out the functions's names that are checked?

**Comment by wchodor** [comment]
I think there are those documentation pages left:
- `createEmptyGithubRepo` 
- `cloneGithubRepo`
- `archive`
- `?agithub` - `githubFunctions.R` file
- `shinySearchInLocalRepo`

**Comment by MarcinKosinski** [comment]
Great, thanks for the update.

2015-12-07 18:30 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment]
No problem.

**Comment by wchodor** [comment]
Documentation pages are now checked. There are some bugs which should be fixed in `githubFunctions` left.

**Comment by MarcinKosinski** [comment]
You mean with functionality :)?

2015-12-10 16:19 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment]
Yes. I mean with functionality.

**Comment by MarcinKosinski** [comment]
@wchodor  could you please have a look at new `alink` function? You could please check whether the documentation is understandable and whether the examples work? Normally I would ask you to write this function but I have invented it 45 minutes ago and I need it for tomorrow so I prepared it by myself :)

**Comment by MarcinKosinski** [comment]
You can check the spelling with working on this https://github.com/pbiecek/archivist/issues/172
and then please close this issue.

**Comment by wchodor** [comment]
fixed with https://github.com/pbiecek/archivist/commit/754449c9cbbdd7147ef30da5d6e7ce71d5d63a24
