### ISSUE TITLE
createEmptyGithubRepo - the 'repoDir' argument

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#142]
I think that createEmptyGithubRepo should take both repoName and repoDir arguments, to specify where is should be located on local disk and how it should be named at GitHub.

**Comment by MarcinKosinski** [comment]
This may somehow lead to changes in `?agithub` functions that may be beyond our skills' spectrum :) Moreover, wouldn't it be too complicated for a user?

**Comment by pbiecek** [comment]
First time when I used createEmptyGithubRepo I was quite surprised that the repo was created in the local directory. 
I try to keep all github repositories in one directory and this is not necessary the directory in which I have a knitr report (which will be using github to store artifacts).

So if it is impossible then it is impossible, butI see that the agithub function can do the setwd() on the beginning and then again at the end (after creation of the github repository).

**Comment by MarcinKosinski** [comment]
@pbiecek I've added `repoDir` parameter to the createEmpyGithubRepo. Can you check whether is that what we planned?

**Comment by pbiecek** [comment]
Correct me if I'm wrong, but here repoDir has different meaning than in
createLocalRepo.

if repoDir is missing then repoDir = repo

and then you create a dir
dir.create(file.path(repoDir, repo))

So it is not possible to create repo in the root of github repository
(like here:https://github.com/pbiecek/graphGallery)

but you will have always a directory with repo files in github repository.








2015-12-28 19:29 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> @pbiecek <https://github.com/pbiecek> I've added repoDir parameter to the
> createEmpyGithubRepo. Can you check whether is that what we planned?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/142#issuecomment-167621975>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Ok I think now it should be more clean (I've added a commit).
I am taking in the consideration if repoDir is provided or not.
When user specifes repoDir for createEmptyGithubRepo he must have an extra
folder inside repoDir is it's
different than repo parameter to enable git synchronization.

Do you suggest changing the name to `repoLocal` or something?

2015-12-29 18:12 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
I do not think that a new argument's name is the best solution (it is a solution but adds some complexity).
I guess that the issue pop up only if someone would like to have different name of the github repository than name of local folder.
So, since it's still an experimental feature let's keep it as it is right now.
And by using it we will figure out if it's optimal.
