### ISSUE TITLE
wrappers for push/pull git functions?

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#146]
Do we have wrappers along push/pull for git?

**Comment by MarcinKosinski** [comment]
We have cloneRepo with `cloneGithubRepo`. And for created repo on github we can archive artifact and push it automatically with `archive`. Are you asking about functionality that ill push repository in which artifact's weren't stored with `archive` function??

**Comment by pbiecek** [comment]
I can imagine situation in which one would like to pull repository (if working with collaborators). Also currently I do not see pull before commit.

**Comment by MarcinKosinski** [comment]
This is one-user integration so far:
https://github.com/pbiecek/archivist/issues/110#issuecomment-160009858

2015-11-29 20:26 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
Status:

We don''t have pullRepo function yet.

**Comment by MarcinKosinski** [comment]
I've added `pullRepo` and `pushRepo` which both have additional parameter `...` enabling passing more sophisticated options to `git2r::pull` and `git2r::push` when more complex `conflicts` occure.
