### ISSUE TITLE
plotRepo / aplot / plotGithubRepo, plotLocalRepo

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#147]
I was thinking about `plotRepo` function (or to be consistent with the new terminology: `aplot` function) which would prepare a summary of a current state of the repository in chart/graph/`ggplot` form.

I imagine functionality to work similar to the overloaded plot function for `lm` class, where user can specify which summary-plot he would like to receive.

````{R}
plotRepo('MarcinKosinski', 'Museum', which = 1:3)
aplot('MarcinKosinski/Museum', 4:6)
````

where which parameter specifies the summary-plot type. The result could be a list, so that for few plots one could use `gridArrange` from `gridExtra` to plot few charts/graphs at the same window.

Do we have any wishes on what types of summary-graphs could `aplot`/`plotRepo` return?

1. Cumulative number of artifacts depending on how many days have passed from Repository creation?
2. Summary of the number of various classes of objects in a bar chart? One could use new function `splitTagsRepo` to achieve this graph in an easy way.
3. Cumulative number of tags depending on how many days have passed from Repository creation?
4.
5.

**Comment by pbiecek** [comment]
I think that #144 is more general (not only for ggplot2). 
And here it looks like a call to two functions searchInRepo and grid.arrange. Also this can be done with shinySearch. 
Also I think that plotRepo would be better than aplot. Now we have aread and asearch but a stands for artifact (read artifact and search for artifact). In case of aplot it is about repository not artifact.

**Comment by MarcinKosinski** [comment]
Yes, I ment plotRepo.

2015-11-29 20:32 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
@MarcinKosinski what we are doing with this issue?
I think that createMDGallery is doing great job and plotRepo is no longer needed (createMDGallery is not affected by number of artifacts).

**Comment by MarcinKosinski** [comment]
createMDGallery print's informations about each artifact.

I thought about `plotRepo` as a graphical summary of the state of `Repository` in one or 2 graphs.
I think we could have few plotRepo methods for `Repository` as I mentioned it here https://github.com/pbiecek/archivist/issues/147#issue-119368946


The number 2 could be obtained with such a code

````{R}
library(ggplot2)
splitTagsGithub(repo = 'graphGallery', user = 'pbiecek') %>%
	group_by(tagKey) %>%
	summarise(count = n()) %>%
	arrange(desc(count)) %>%
	ggplot(aes(reorder(tagKey, count, max), count)) +
	geom_bar(stat = "identity") +
	theme_minimal() + xlab('Number of entries with this Tag') + ylab('Tags') +
	ggtitle('Barplot of counts of Tags\' types in pbiecek/graphGallery Repository')
```` 

I could prepare 2 more methods if we don't have more ideas about summary plots

**Comment by pbiecek** [comment]
@MarcinKosinski are you going to do this for v2.0 or leave it for now? 
I think that your snippet is doing the job and we do not need additional functions

**Comment by MarcinKosinski** [comment]
Let's leave if for possible future and then reopen if one has a time and
ideas for this.
close #147

2016-02-08 2:03 GMT+01:00 Przemysław Biecek <notifications@github.com>:
