### ISSUE TITLE
`asearch` function usage

### ISSUE THREAD

**Issue by wchodor** [pbiecek/archivist#149]
@pbiecek 
I am in the course of reviewing `asearch` function and I'm wondering what was your goal. Were you planning to extend its functionality on local repository? This part of `asearch` function's body indicates that we want to search and read from local repo too. But it can be only default local repo. 
```
if (is.null(repo)) {
    # use default repo
    oblist <- multiSearchInLocalRepo(patterns = patterns,
                                      intersect = TRUE)
    if (length(oblist)>0) {
      res <- lapply(oblist, aread)
    } 
  }
```
I am a little bit confused because the documentation suggests that we want to work on Github Repository only.

**Comment by MarcinKosinski** [comment]
I think it's just the matter of obsolete documentation.

**Comment by pbiecek** [comment]
The documentation is to be updated.
My goal is to cover to options:
If there is any '/' then it search in github repo,
If there is no / then it search in the default repo, either local or github.

P

Dnia 30.11.2015 o godz. 14:20 Witold Chodor <notifications@github.com> napisał(a):

**Comment by wchodor** [comment]
So tha actual code won't work for Github  default repository. Do you want me to take care of it?

**Comment by pbiecek** [comment]
Would be great if you can take care of it.

2015-11-30 16:14 GMT+01:00 Witold Chodor <notifications@github.com>:

> So tha actual code won't work for Github default repository. Do you want
> me to take care of it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/149#issuecomment-160657463>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by wchodor** [comment]
@pbiecek 
I made some changes and now it is working. I would appreciate if you tell me whether such changes meet you expectations. Here is the link to commit:
https://github.com/wchodor/archivist/commit/b7bef3279b8e8ba6fb0a85c43f1e7015b2f41811

**Comment by wchodor** [comment]
@MarcinKosinski @pbiecek 
What is more I suggest removing `default` parameter from `createEmptyLocalRepo` function. 
First of all because of the fact that it is not used in createEmptyGithubRepo.
Secondly `asearch` won't work with `default=TRUE` argument in createEmptyLocalRepo.

**Comment by MarcinKosinski** [comment]
There's an issue for default parameter in createEmptyGithubRepo:
https://github.com/pbiecek/archivist/issues/143

Why asearch won't work with default=TRUE argument in createEmptyLocalRepo?


2015-12-01 18:04 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment]
Because of `setLocalRepo`. I assumed that `type` parameter is loaded into `.ArchivEnc` in `setRepo` function. So when you are using `createEmptyRepo` with `default=TRUE` parameter then `type` is not loaded. And `multiSearchInRepo` in `asearch` gives an error.

**Comment by MarcinKosinski** [comment]
So maybe createEmptyRepo with default=TRUE should also change global `type`
parameter?

2015-12-01 18:15 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment]
IDo you mean to put 
```
aoptions( "type", type )
```
in createEmpty Repo' body?

**Comment by wchodor** [comment]
```
stopifnot(is.character(type) & length(type) ==1 & type %in% c("local", "github"))
aoptions( "type", type )
  if (type == "local") {
    createEmptyLocalRepo(repoDir = repoDir, force = force, default = default)
  } else {
```

**Comment by MarcinKosinski** [comment]
if deafult == TRUE ?

2015-12-01 18:54 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment]
```
  stopifnot(is.character(type) & length(type) ==1 & type %in% c("local", "github"))
  if (default) aoptions("type", type)
  if (type == "local") {
    createEmptyLocalRepo(repoDir = repoDir, force = force, default = default)
  } else {
```

**Comment by MarcinKosinski** [comment]
Looks good. Pleas do the change and submit PR

2015-12-01 18:58 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by pbiecek** [comment]
Why do we need 'type = aoptions("type")' ?
It looks like a duplication, since the loadFromRepo() function can decide
if someone is asking for local repo (repoDir is set)
or github repo (repo is set).

it is actually a possible vulnerability since default value of type may not
be consistent with default value of  repoDir/repo.



2015-12-01 17:56 GMT+01:00 Witold Chodor <notifications@github.com>:

> @pbiecek <https://github.com/pbiecek>
> I made some changes and now it is working. I would appreciate if you tell
> me whether such changes meet you expectations. Here is the link to commit:
> wchodor@b7bef32
> <https://github.com/wchodor/archivist/commit/b7bef3279b8e8ba6fb0a85c43f1e7015b2f41811>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/149#issuecomment-161030198>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment]
Regarding the 'default' parameter (let's use separate issues for separate
problems),
I would rather fix asearch (to make it working with default local repo) and
createEmptyGithubRepo (which is still in development I believe)


2015-12-01 18:04 GMT+01:00 Witold Chodor <notifications@github.com>:

> @MarcinKosinski <https://github.com/MarcinKosinski> @pbiecek
> <https://github.com/pbiecek>
> What is more I suggest removing default parameter from
> createEmptyLocalRepo function.
> First of all because of the fact that it is not used in
> createEmptyGithubRepo.
> Secondly asearch won't work with default=TRUE argument in
> createEmptyLocalRepo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/149#issuecomment-161033229>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment]
The fact that you need to synchronise changes in 'type' and 'repoDir' is an
argument against using `type` as a parameter.
Instead of that (if we really need `type`, I am not convinced) it may be a
function which will decide if the definition of a repository matches local
repo or github repo (it can be decided based of names of arguments).

2015-12-01 19:01 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Looks good. Pleas do the change and submit PR
>
> 2015-12-01 18:58 GMT+01:00 Witold Chodor <notifications@github.com>:
>
> > stopifnot(is.character(type) & length(type) ==1 & type %in% c("local",
> "github"))
> > if (default) aoptions("type", type)
> > if (type == "local") {
> > createEmptyLocalRepo(repoDir = repoDir, force = force, default = default)
> > } else {
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pbiecek/archivist/issues/149#issuecomment-161047884
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/149#issuecomment-161048692>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by wchodor** [comment]
OK, I think that I understand you. I will try to fix it once again.

**Comment by wchodor** [comment]
I made some changes regarding your hints. Above you have my commit.

**Comment by pbiecek** [comment]
Thanks, 
btw: maybe we can add to the wiki list of parameters, that can be set via 'aoptions'?
Then it will be easier to see parameters like 'type'

**Comment by wchodor** [comment]
When it comes to `type` I removed it and used `repoDir` and `repo` arguments to detect whether repository is local o GitHub.

**Comment by MarcinKosinski** [comment]
Ok looks good. If this is fixed, can you @wchodor close the issue?
