### ISSUE TITLE
`cache` function's body

### ISSUE THREAD

**Issue by wchodor** [pbiecek/archivist#150]
I' am wondering why do we need `call` atribute in the output of `cache` function?
```
 output <- do.call(FUN, list(...))
  attr( output, "tags") <- paste0("cacheId:", outputHash)
  attr( output, "call") <- "" 
```

**Comment by pbiecek** [comment]
The call atribute was there, the line
attr( output, "call") <- "" 
removes it

**Comment by wchodor** [comment]
So perhaps we should write:
```
attr( output, "call") <- NULL
```
Then it will be completely removed. I'm asking because if somebody will call `cache` he will receive output with `tags` and `call` attributes and I think that 'call' is not necessary.

**Comment by pbiecek** [comment]
Generic functions like 'print' expects this attribute for some objects
For example for lm() the print.lm expects it, so I am not sure how print.lm
will behave if the call is removed.


2015-11-30 18:57 GMT+01:00 Witold Chodor <notifications@github.com>:

> So perhaps we should write:
>
> attr( output, "call") <- NULL
>
> Then it will be completely removed. I'm asking because if somebody will
> call cache he will receive output with tags and call attributes and I
> think that 'call' is not necessary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/150#issuecomment-160706450>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
So if you are not changing anything, can you resolve this issue?
