### ISSUE TITLE
default parameter for cloneGithubRepo

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#171]
add a functionality allowing to set cloned repo from github as defualt local and default github one :)

**Comment by MarcinKosinski** [comment]
@wchodor Do you think you could do that?

**Comment by MarcinKosinski** [comment]
You can have a look at the beggining of `createEmptyGithubRepo` - remeber then to add information about this change to the `NEWS.md`

**Comment by wchodor** [comment]
I will try...
