### ISSUE TITLE
alink function: extend functionality for branch and repoDir

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#172]
Could you please have a look at new function and extend it's functionality to work with `branch` and `repoDir` argument?

**Comment by MarcinKosinski** [comment]
@wchodor could you please handle this issue? The commit is above?

**Comment by wchodor** [comment]
I will do my best to fulfill this mission:)

**Comment by wchodor** [comment]
You mean `branch` and `repoDirGit` arguments?

**Comment by MarcinKosinski** [comment]
Yes

2015-12-18 9:44 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment]
Closed due to `aread` function that doesn't take `branch` and `repoDirGit` parameters into consideration.
