### ISSUE TITLE
check parameters in saveToRepo

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#173]
@wchodor could you kindly please extend this check to assure that the parameter length is equal to 1? https://github.com/pbiecek/archivist/blob/master/R/saveToRepo.R#L285
What do you think about subtituting all parameter to default `aoptions` as mentioned in #102 ?

**Comment by wchodor** [comment]
OK, I can handle this. To be honest. I prefer the idea of default parameters in a normal way. But it is true that the code should be consistent. So either we use `aoptions()` everywhere or nowhere.

**Comment by MarcinKosinski** [comment]
I like the idea of setting options globally once:

````{R}
aoptions(list_of_options)
````

and then running 1000 commands with simple syntax

````{R}
archive(artifact1)
archive(artifact2)
archive(artifact3)
...
archive(artifact1000)
````

instead of non setting options globally and recoping them 1000 times

````{R}
archive(artifact1, list_of_options)
archive(artifact2, list_of_options)
archive(artifact3, list_of_options)
...
archive(artifact1000, list_of_options)
````

2015-12-11 8:26 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment]
Ok, now I can see why you need it. And taking it into consideration I agree that it is worth setting options globally.

**Comment by wchodor** [comment]
I think that you asked to make alterations in `saveToRepo` :). The link to commit is above.
