### ISSUE TITLE
What is needed to support bitbucket or other git repositories?

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#178]

**Comment by pbiecek** [comment]
I've created git and mercurial repos on BitBucket (for testing):
Git
https://bitbucket.org/pbiecek/graphgallerygit/src
Mercurial
https://bitbucket.org/pbiecek/graphgallerym/src

**Comment by MarcinKosinski** [comment]
What about 

- https://gitlab.com/
- http://www.fogcreek.com/kiln/
- https://www.heroku.com/

**Comment by pbiecek** [comment]
So many to choose ;-)
Also private company git/hg systems.
I will look for some common interface. Maybe there is some

**Comment by pbiecek** [comment]
Maybe it's enough to change path to Github file.
For bitbucket one can access to files like that:

(load(url("https://bitbucket.org/pbiecek/graphgallerym/raw/b1665c98645521562ea7f56e03e453099d14ce84/gallery/02af4f99e440324b9e329faa293a9394.rda")))

Both mercurial and github files

**Comment by MarcinKosinski** [comment]
Is this related/similar to #191  ?

**Comment by pbiecek** [comment]
This one should be done first in order to do #191 properly

**Comment by MarcinKosinski** [comment]
I've seen a great work you've done in this issue. It looks impresive.
Recently I've added an information for developers https://github.com/pbiecek/archivist/wiki/For-developers (copied and merge from several resources) in which there is a strong enhancement for updating `NEWS.md`

> The NEWS.md file also has to be updated while fixing or implementing an issue. It should mention the issue number (along with the link) and what the issue is being closed. 

Could you please extend `NEWS.md` in the moment you'll finish this issue?
