### ISSUE TITLE
What is needed to support other languages?

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#179]
Only changes in the artifact table in database?

**Comment by pbiecek** [comment]
An idea: in repository artifacts are stored in different formats. And language recognises how to load this object. i.e. python version of archivist  can share same repository with R. The repository can be used to share artifacts across languages

**Comment by MarcinKosinski** [comment]
additional tag to artifact specifying the language?

````{R}
extractTags.default <- function( object, objectNameX, ... ) {
  name <- paste0( "name:", objectNameX )
  class <- paste0( "class:", class( object ) )
  date <- paste0( "date:", now() )
  language <- "language:R"
  return( c( name, class, date, language ) )

}

````

**Comment by pbiecek** [comment]
I guess that we need to change readFromRepo and saveToRepo as well (if we decide to go this direction).
Anything else will require to be changed?

**Comment by MarcinKosinski** [comment]
If we only want to add additional Tag : `language`, then I think only
changes in saveToRepo should be done in
https://github.com/pbiecek/archivist/blob/master/R/extractTags.R which also
affects `archive`.

Talking about loadFromRepo - this only reads `.rda` files, so probably
there is no need to change anything (or only in the case of md5hash
abbreviation we should add additional **WHERE tag = 'language:R'**
statement when we are trying to load all matching md5hashes
https://github.com/pbiecek/archivist/blob/master/R/loadFromRepo.R#L285-L287

2016-01-10 22:19 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
The reviewer asked about other languages. Ant this makes me wonder how hard it will be to load in R objects created in Julia/python. And vice versa

Also, thinking about lazy data (for R) maybe we can do both things at once, supporting different formats.
In the first version of archivist there was support for excel files as well. It was not a good idea then. But now, maybe some support for csv?

I am not convinced if it's a lot of work. But maybe it's not?

**Comment by MarcinKosinski** [comment]
If there are any converters for .rda files for python and vice versa for
python objects (whathever they are) this probably will be the case of using
converter  instead of `load` here
https://github.com/pbiecek/archivist/blob/master/R/loadFromRepo.R#L308-L310

2016-01-10 22:42 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
In python one can read rda
http://sourceforge.net/p/rpy/mailman/message/21330579/

vice versa it should be also possible (most python formats are text based)
let's discuss it tomorrow

**Comment by pbiecek** [comment]
Proposition: language does not matter, only format matter.
One could write to rda file in R or in julia and it is not important where the write takes place. Only format is important to verify if given artifact can be loaded from other languages.

**Comment by MarcinKosinski** [comment]
I agree. Additional tag or Column?

Marcin Kosinski

Dnia 27.01.2016 o godz. 22:20 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
Let's try it as a additional tag, working on this now

**Comment by andersrmr** [comment]
where did this subject end up? is there comparable functionality to `archivist` for python?
