### ISSUE TITLE
Integration with Sweave/knitr

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#180]
An use-case with overridden print function for gg class?
Like here: https://github.com/pbiecek/Eseje/blob/master/GamatykaGrafiki.Rmd

**Comment by MarcinKosinski** [comment]
is this the same as #74 ? or this is use case for that functionality?

**Comment by pbiecek** [comment]
imho pin is closely related with github. It takes care about integration with github but do not care if knitr is used or not. And you need to actively point which objects should be archived.

While here we do not need github at all. 
We may include links to dropbox repositories/google drive repos or anything that user can implement.
All objects of given class will be archived.

**Comment by MarcinKosinski** [comment]
In your example you provide `hooks` that directs to the object stored on GitHub. Maybe you would like to change the link under the `hook` that the object would automatically be downloaded (as it is done in `alink` function,  `archive` (for `alink = TRUE`) `ahistory` (for `alink = TRUE`))?

**Comment by pbiecek** [comment]
Next time I will use alink.
I've tested the generation of README.md (as here: https://github.com/pbiecek/Eseje/tree/master/arepo), functionality is impressive bur calls might be simplified. It took me some time to understand why repoDirGit has to be FALSE for root directory, sometimes it's logical value sometimes it's character. Maybe NULL instead of FALSE will be more consistent?
Anyway, will try alink in next occasion.

**Comment by MarcinKosinski** [comment]
repoDirGit is probably set to FALSE in other functions that interacts with github. So it's probably done in this way to maintain consistency

Marcin Kosinski

Dnia 28.01.2016 o godz. 20:35 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
We have two approaches how to integrate with git( repos.
@MarcinKosinski  shall we close this issue?

**Comment by MarcinKosinski** [comment]
@pbiecek  you mean with `archive`/`alink` and `pin`/`addHooks ?
I thinks this is almost the same as #74 so we can close this issue.
