### ISSUE TITLE
What is needed to support other, non R formats like csv/json

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#181]
Just an open question. How hard it will be to introduce non R formats. 
Maybe this has no sense (problems with md5hashes) but maybe it is possible?
What are pros/cons.

**Comment by MarcinKosinski** [comment]
We can store json/csv/txt files in a separate folder than `gallery`, with their metadata (`Tags`) specified by a user.

**Comment by pbiecek** [comment]
What about storing all formats in the gallery folder?
The file extension will identify the file format.
Then the R function will know how to read it based on it's extension.

**Comment by MarcinKosinski** [comment]
@pbiecek could you please remind me what have we decided about supporting other non R formats like csv/json ?

**Comment by pbiecek** [comment]
I think that in close future we will support only rda files.
But the format and language will be added as tag to the repo (saveToRepo will do this).
so in future these tags may be used.

**Comment by MarcinKosinski** [comment]
As an additional `Tag` or as an additional column?

**Comment by pbiecek** [comment]
We have talked about this and I was for additional column.
But now I think it's relation 1 to many.
One object could be stored in many formats (rda / csv / text / json / png).
So it will be easier to store this information as a `Tag`.
Also this way we will avoid changes in the structure of the database.

**Comment by MarcinKosinski** [comment]
I remember your approach. I'm asking whether you have change your mind and I think that's the less troublesome solution.

**Comment by pbiecek** [comment]
I'ce changed my mind.

**Comment by pbiecek** [comment]
In 2118c10125403429a35b3569d057347165874338 I've added tags related to format.
Both miniature and artifact leaves information about formats that are in gallery folder for given artifact. Currently only rda/txt/png are supported

**Comment by pbiecek** [comment]
I do not think that we are able to add some deeper support for non R objects. Let's stick with additional tags in repo. Having them some more sophisticated support may be added later

**Comment by MarcinKosinski** [comment]
If new tags are done, You can add an iformation to `NEWS.md` file (also linking to this issue), and close this issue.

**Comment by MarcinKosinski** [comment]
I don't Have a vision for that neither. But additional information in NEWS.md about new Tags would be helpfull. 

Marcin Kosinski

Dnia 30.01.2016 o godz. 12:15 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
added.

**Comment by MarcinKosinski** [comment]
By the way, you can always add '#issue_number' to the commit message, so that commit will appear in the issue tree (i.e. commit message ; "updated NEWS.md for #181")
