### ISSUE TITLE
Reimplement loadFromRepo

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#182]
The implementation looks horrible and probably is anti-user-friendly.

**Comment by pbiecek** [comment]
Are you going to work on that?
If not I can handle this issue

**Comment by MarcinKosinski** [comment]
I think loadFromRepo, and potentional other `wrappers` should be removed
since it is almost useless now:
`
https://github.com/pbiecek/archivist/commit/b7bef3279b8e8ba6fb0a85c43f1e7015b2f41811#commitcomment-15774236`
and creates a lot of unnecessary problems.

I was thinking about creating a second package: `archivist.S4` where
repository would an an object of class `arepo` working more or less like
this: https://github.com/pbiecek/archivist/issues/153#issuecomment-167820247


2016-01-30 12:18 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
I don't think that a new package will help here. 
We should first make this package more consistent and polished.

I'm ok with abandoning general wrappers for now.
Let's first close the development of new features.

**Comment by pbiecek** [comment]
loadFromRepo is used only in aread and asearch

**Comment by pbiecek** [comment]
obsolete with #189

**Comment by MarcinKosinski** [comment]
Ok we have removed `loadFromRepo` from `asearch` but this function is still visible/exported. I would insist on not-exporting this function.

**Comment by pbiecek** [comment]
Ok

2016-02-01 23:48 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Ok we have removed loadFromRepo from asearch but this function is still
> visible/exported. I would insist on not-exporting this function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/182#issuecomment-178238780>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek
