### ISSUE TITLE
setRepo

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#183]
Do we need to export `setLocalRepo` and `setGithubRepo` since we have `aoptions` function?
If we'd move them to depracated (if one would use those functions, they will not work but will print additional information that this is not supported anymore and one should use `aoptions`) then after few substitutions in functions' examples we could remove those 2 functions. The less functions there is the more clear a package is IMHO - `aoptions` does the work.

@pbiecek  what do you think about that?

**Comment by pbiecek** [comment]
Yes they are redundant.
But I'm afraid that hiding of setLocalRepo may break some existing functionality. 
We may add the 'deprecated' tag, but let's not remove it until the version 2.0

**Comment by MarcinKosinski** [comment]
So maybe let's **reopen** this issue when we'll be thinking about 2.0
