### ISSUE TITLE
Documentation build with roxygen2

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#186]
Maybe we should decide on which version of `roxygen2` we are building documentation? I am using +5.0.0 version. When we all have different versions than after each build of the other collaborator the every documentation page changes and the commits start containing unnecessary changes.

**Comment by pbiecek** [comment]
The current version is 5.0.1.
But fortunately this one is not adding version number to Rd files so we should not have this problem any longer.

**Comment by MarcinKosinski** [comment]
Ok, so if everyone is using +5.0.0 then I am closing this issue
