### ISSUE TITLE
markdown malformes " in alink

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#188]
" is replaced by ”
and is not working after being copied to R

**Comment by pbiecek** [comment]
fixed with 9803ce9ce43372f00c590f542aa44e647060f2b9

**Comment by pbiecek** [comment]
Fixed and here is working example: 
file:///Users/pbiecek/GitHub/PieczaraPietraszki/UniwersytetDzieci/prezentacja.html

**Comment by MarcinKosinski** [comment]
Thanks.
Working example is on your local machine?
Maybe you could upload it to ghPages directory?

**Comment by pbiecek** [comment]
Sorry, should be 
https://rawgithub.com/BetaAndBit/PieczaraPietraszki/master/UniwersytetDzieci/prezentacja.html

**Comment by MarcinKosinski** [comment]
Wow, thanks for that. I have seen a problem with previous quotes but couldn't find a solution.
