### ISSUE TITLE
add Git/Remote copies for all Github functions

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#191]
Just add new names, to make it consistent with #187

**Comment by pbiecek** [comment]
@MarcinKosinski If we are going to support other git repositories we shall do something with the 'Github' in names of current functions.

I think that the easier solution is to add new symbols like
loadFromGitRepo <- loadFromGithubRepo

This will:
1. mess the NAMESPACE (more functions with similar names) but I would not remove Gihtub functions since some users may be already use to them
2. make it more natural to support other non Github repositories

We may consider something like 
loadFromGlobalRepo instead of Git repo 
since mercurial bitbucket repos will be supported as well. 

What do you think?

**Comment by MarcinKosinski** [comment]
loadFromRemoteRepo?

**Comment by MarcinKosinski** [comment]
We won't have similar names, and remote also stands for other github-like
platforms that are not local :)

2016-01-30 22:46 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
Ok, 'Remote' will be also more consistent with the article

**Comment by MarcinKosinski** [comment]
If we are planning to move from `*GithubRepo` to `*RemoteRepo` names, maybe we could consider changing `repoDirGit` parameter name to `subdir` ?

**Comment by pbiecek** [comment]
For now I will keep copy of *GithubRepo (as in current loadFromRemoteRepo / loadFromGithubRepo)
Just in case that someone is using this functions.

I like the `subdir` for loadFromRemoteRepo, since other arguments are baed on single words (`user`/`repo`)

**Comment by MarcinKosinski** [comment]
Ok. I like the idea of `Remote` name instead of `Github` . I am aware of that some codes might be based on `*GithubRepo` functions. Thinking about having as least functions as possible it'll be crucial in the future to abandon `*GithubRepo` convention.

**Comment by MarcinKosinski** [comment]
What about parameters' convention as in `devtools::install_github`? 

> repo - Repository address in the format username/repo[/subdir][@ref|#pull]. 

We could name this parameter as `remote`

**Comment by pbiecek** [comment]
QL, 
maybe we can use some functions from devtools to download files from git/bitbucket/github
I see that they have overloaded remote_download for bitbucket_remote / svn and others
But it works for whole repo as zip file so there may be some problems for single files

**Comment by MarcinKosinski** [comment]
For GitHub we are doing it in a `smarter` way. We download only one file
for it's raw URL.
I think one should understand they way in which URL for bitbucket should be
provided so that only 1 file will be downloaded if needed.

2016-02-01 0:15 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
getRemoteHookBitbucket may be used to download only one file
