### ISSUE TITLE
ahistory non-suitable parameters' names

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#193]
One can see [here](https://htmlpreview.github.io/?https://github.com/pbiecek/archivist/blob/master/ghPage/Pedigree_Retrieval.html#with-hooks) (but I don't know why the resulted table didn't form to the way it appeared locally) that with `ahistory()` one can prepare a table with artifact's pedigree where md5hashes of partial results are presented with hooks to the github repository.

One could pass arguments like

````{R}
ahistory(artifact, format = "kable", repoDir = "Pedigree_Example", alink = TRUE,
         user = "MarcinKosinski", repo = "Museum")
````

where `repoDir`, `user` and `repo` are further arguments passed by `...` to the `alink()` function.
It looks weird, since `repoDir` is required to extract history of the object, that is seeked in the Local `Repository`. Even though `user` and `repo` is set globally with `aoptions('repo/user', value)` and one would like to pass only `repoDir` parameter like this

````{R}
ahistory(artifact, format = "kable", alink = TRUE, repoDir = "Pedigree_Example")
````

the above code won't work **because repoDir will parameter will be treated as `repo` parameter**. 
And probably more functions that use `alink` with `...` will not work also for the same reason - have you noticed this in the `addHooks`?

This is very odd behaviour of R and makes the code to be unbearable. Do you @pbiecek have any suggestion on how to overcome this burdensomeness ?

**Comment by pbiecek** [comment]
@MarcinKosinski is tis issue still valid? I've assumed that ahistory is working for local repo.  Is it not the full truth?

**Comment by MarcinKosinski** [comment]
If `repoDir` has been changed to `subdir` (ths issue https://github.com/pbiecek/archivist/issues/205) so there shouldn't be such conflict right now.

**Comment by MarcinKosinski** [comment]
Moreover when one pass `format = 'kable'` and `alink = TRUE` then one can use links for Remote repository. But hashes are taken from Local Repository. So I think this might be closed.

**Comment by MarcinKosinski** [comment]
This is the only change I would recommend, so you can feel free to take `token for changes`.

**Comment by pbiecek** [comment]
Ok, sounds good

2016-02-09 13:44 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> This is the only change I would recommend, so you can feel free to take token
> for changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/193#issuecomment-181848444>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek
