### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#197]
Remote instead of GitHub everywhere
Move Git dependent things to archivist.github

**Comment by MarcinKosinski** [comment]
#198 + remember to update `NEWS.md` so that things that appear only in 1.9 and were removed 1.9 are no longer in `NEWS.md` +  add informations about new things

One closed issue  = one more bullet-point in `NEWS.md`

**Comment by MarcinKosinski** [comment]
https://github.com/MarcinKosinski/archivist.github
