### ISSUE TITLE
Move functions using git2r and GitHub API to archivist.git2r / archivist.github package

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#198]
Remove documentation for and functionalities of

- `archive`
- `pushRepo`
- `pullRepo`
- `deleteGithubRepo` (also update deleteRepo)
- `createGithubRepo` (also update createRepo)
- `cloneGithubRepo`
- `?agithub` man page

**Comment by pbiecek** [comment]
@MarcinKosinski do you need help in this? I can move this files today

**Comment by MarcinKosinski** [comment]
If you have more time then feel free. I was planning to do this in the
evening, but if this is better for you to do this earlier that it's ok for
me :)

2016-02-07 10:24 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
I have transfered mentioned  above functions to https://github.com/MarcinKosinski/archivist.github

When I have implemented such integration I have changed `createEmptyRepo` to `createEmptyLocalRepo` and `deleteRepo` to `deleteLocalRepo`. For now we have 4 of them.
Should we leave only `createEmptyLocalRepo` and `deleteLocalRepo` and more `createEmptyRepo` and `deleteRepo` to deprecated?

After this is resolved I'll update `NEWS.md`

**Comment by pbiecek** [comment]
I think that we should have either:
- short functions like aread, asearch
- full names, but here obligatory with either Local or Remote.
(so deleteRepo - deprecated, deleteLocalRepo - default)
- btw: maybe instead createEmptyLocalRepo we shall have createLocalRepo?
then createEmptyLocalRepo may be deprecated

2016-02-07 22:14 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> I have transfered mentioned above functions to
> https://github.com/MarcinKosinski/archivist.github
>
> When I have implemented such integration I have changed createEmptyRepo
> to createEmptyLocalRepo and deleteRepo to deleteLocalRepo. For now we
> have 4 of them.
> Should we leave only createEmptyLocalRepo and deleteLocalRepo and more
> createEmptyRepo and deleteRepo to deprecated?
>
> After this is resolved I'll update NEWS.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/198#issuecomment-181118522>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Sounds good since I've  added createGitHubRepo (without Empty) to
archivist.github

2016-02-07 22:25 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
Now I think that we could gather `archive`, `createGithubRepo`, `deleteGithubRepo`, `cloneGithubRepo`, `puchGithubRepo` and `pullGithubRepo` into one function, i.e. `archive` / `agithub` and this function could have `method` parameter which for 

- `method = "create"` would trigger `createGithubRepo`
- `method = "delete"` would trigger `deleteGithubRepo`
- `method = "clone"` would trigger `cloneGithubRepo`
- `method = "pull"` would trigger `pullGithubRepo`
- `method = "push"` would trigger `pushGithubRepo`

This is really simple functionality, and even when moving those functions to other package I thought I could create one function from them. I'm not so sure right now whether additional package is needed :)

**Comment by pbiecek** [comment]
The nice thing about a new package is that there may be other extensions as
well,
like you have suggested archivist.dplyr or archivist.bitbucket.

Then we may really stop development of archivist and freeze changes here.
All extensions will be added to these new packages.

I am a bit afraid that always there will be something worth to add, but on
some point we should say that tis version is ''production ready' and users
should not bother that new things will come in a month or something



2016-02-09 13:48 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Now I think that we could gather archive, createGithubRepo,
> deleteGithubRepo, cloneGithubRepo, puchGithubRepo and pullGithubRepo into
> one function, i.e. archive / agithub and this function could have method
> parameter which for
>
>    - method = "create" would trigger createGithubRepo
>    - method = "delete" would trigger deleteGithubRepo
>    - method = "clone" would trigger cloneGithubRepo
>    - method = "pull" would trigger pullGithubRepo
>    - method = "push" would trigger pushGithubRepo
>
> This is really simple functionality, and even when moving those functions
> to other package I thought I could create one function from them. I'm not
> so sure right now whether additional package is needed :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/198#issuecomment-181850437>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
You've convinced me once again. Let's have archivist.github :)

2016-02-09 13:54 GMT+01:00 Przemysław Biecek <notifications@github.com>:
