### ISSUE TITLE
repoDirGit = "/" instead of FALSE

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#203]
in unix systems the root directory is denoted as "/". Shall we use here same notation?

**Comment by pbiecek** [comment]
@MarcinKosinski  what do you think about this? The "/" may be more intuitive than FALSE.

And second question: Are we keeping the name repoDirGit? we can change it to remoteDir

**Comment by MarcinKosinski** [comment]
I would change `repoDirGit` to `subdir` as this is more popular for such cases. Also one could provide repo parameter as `repo = "user/repo[/subdir]"` as it is done in `devtools::install_github()`.

The "/" is more intuitive than `FALSE` and if we are refactoring this much then it is a good idea to clean this messy parameter. I can't remember why did we decided to use `FALSE`.

**Comment by pbiecek** [comment]
done

2016-02-07 12:34 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> I would change repoDirGit to subdir as this is more popular for such
> cases. Also one could provide repo parameter as repo =
> "user/repo[/subdir]" as it is done in devtools::install_github().
>
> The "/" is more intuitive than FALSE and if we are refactoring this much
> then it is a good idea to clean this messy parameter. I can't remember why
> did we decided to use FALSE.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/203#issuecomment-180998409>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek
