### ISSUE TITLE
alink function

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#207]
what about `alink` function in terms of https://github.com/pbiecek/archivist/issues/198 ?
It only uses github functionality.

**Comment by pbiecek** [comment]
Is used in addHooksToPrint
So probably it will be refactored.

**Comment by MarcinKosinski** [comment]
Ok so I'm not exporting this to https://github.com/MarcinKosinski/archivist.github 
which is almost done, so I can now remove confusing functions from `archivist`

**Comment by pbiecek** [comment]
Will add support for bitbucket / local repos

**Comment by pbiecek** [comment]
btw: it was not supporting the 'branch' argument

**Comment by MarcinKosinski** [comment]
I think it was not supporting `branch` because of past limited version of
`aread` that also did not react on branch and subdir

2016-02-08 1:54 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
How can we mention this in `NEWS.md`?

**Comment by pbiecek** [comment]
Are you talking about alink? 
It's already in NEWS (for v1.9) I do not see anything that should be added

**Comment by MarcinKosinski** [comment]
I'm confused since we'll be publishing 2.0 on CRAN and one might not have a
look at 1.9.
In the 1.9 we've added information that alink gives hooks only for `Github`
so we could merge 1.9 and 2.0 info version, pretending that 1.9 was nerver
there and all new features are for 2.0, and then in a link we could write
that it supports Github and Bitbucket.

I can merge NEWS.md for 1.9 and 2.0

2016-02-08 12:07 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
For CRAN, since last CRAN version was 1.8 then I think all changes in 1.9
and 2.0 should be read.
I do not think that merging NEWS for 1.9 and 2.0 is a good idea, since then
they will not be consistent with github.

But imagine a situation that for some reason somebody was using archivist
1.0.
Then he should read NEWS for 1.1+. And it's not like we should merge
1.1..2.0

So I think current NEWS file is in a good shape


2016-02-08 12:12 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> I'm confused since we'll be publishing 2.0 on CRAN and one might not have a
> look at 1.9.
> In the 1.9 we've added information that alink gives hooks only for `Github`
> so we could merge 1.9 and 2.0 info version, pretending that 1.9 was nerver
> there and all new features are for 2.0, and then in a link we could write
> that it supports Github and Bitbucket.
>
> I can merge NEWS.md for 1.9 and 2.0
>
> 2016-02-08 12:07 GMT+01:00 Przemysław Biecek <notifications@github.com>:
>
> > Are you talking about alink?
> > It's already in NEWS (for v1.9) I do not see anything that should be
> added
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pbiecek/archivist/issues/207#issuecomment-181309602
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/207#issuecomment-181312493>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
You've convinced me. If `all github functions are now remote` functions
refers to alink then we are clear about this :)

2016-02-08 12:27 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
I've just added a more specific info related directly to alink. Just in case

2016-02-08 12:45 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> You've convinced me. If `all github functions are now remote` functions
> refers to alink then we are clear about this :)
>
>
> 2016-02-08 12:27 GMT+01:00 Przemysław Biecek <notifications@github.com>:
>
> > For CRAN, since last CRAN version was 1.8 then I think all changes in 1.9
> > and 2.0 should be read.
> > I do not think that merging NEWS for 1.9 and 2.0 is a good idea, since
> then
> > they will not be consistent with github.
> >
> > But imagine a situation that for some reason somebody was using archivist
> > 1.0.
> > Then he should read NEWS for 1.1+. And it's not like we should merge
> > 1.1..2.0
> >
> > So I think current NEWS file is in a good shape
> >
> >
> > 2016-02-08 12:12 GMT+01:00 Marcin Kosiński <notifications@github.com>:
> >
> > > I'm confused since we'll be publishing 2.0 on CRAN and one might not
> > have a
> > > look at 1.9.
> > > In the 1.9 we've added information that alink gives hooks only for
> > `Github`
> > > so we could merge 1.9 and 2.0 info version, pretending that 1.9 was
> > nerver
> > > there and all new features are for 2.0, and then in a link we could
> write
> > > that it supports Github and Bitbucket.
> > >
> > > I can merge NEWS.md for 1.9 and 2.0
> > >
> > > 2016-02-08 12:07 GMT+01:00 Przemysław Biecek <notifications@github.com
> >:
> > >
> > > > Are you talking about alink?
> > > > It's already in NEWS (for v1.9) I do not see anything that should be
> > > added
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/pbiecek/archivist/issues/207#issuecomment-181309602
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/pbiecek/archivist/issues/207#issuecomment-181312493
> > >.
> > >
> >
> >
> >
> > --
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pbiecek/archivist/issues/207#issuecomment-181324699
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/207#issuecomment-181331517>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek
