### ISSUE TITLE
objectName/artifactName parameter in saveToRepo

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#208]
@pbiecek What would you say about adding `objectName/artifactName` by default set to `artifactName = deparse( substitute( artifact ) )` ?

This would only affect this line which could be commented out
https://github.com/pbiecek/archivist/blob/master/R/saveToRepo.R#L300

This could be helpful in `archive` function which so has most of the code copied from `saveToRepo` because of the problem with passing names to many sub-environments. What do you think about that?
Then the code of `archive` could be more readable and clear.

**Comment by MarcinKosinski** [comment]
If that's ok then you can merge this PR https://github.com/pbiecek/archivist/pull/209

**Comment by pbiecek** [comment]
merged.
I've removed commented lines for saveToRepo2 (no idea what had been implemented there) and changes check for artifactName (should be is.character not is.logical.

**Comment by MarcinKosinski** [comment]
Ok thanks. saveToRepo2 was an idea for archiving other formats that `.rda` (i.e. `.rds`).
