### ISSUE TITLE
shorten examples in all functions

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#210]
They are too long and can be created with the usage of `Repository` that is embed in the package

**Comment by pbiecek** [comment]
Good idea, but when?
Is is planned as a pre 2.0 feature?



2016-02-07 22:16 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> They are too long and can be created with the usage of Repository that is
> embed in the package
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/210>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
I am doing it right now

2016-02-07 22:27 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
QL

2016-02-07 22:31 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> I am doing it right now
>
> 2016-02-07 22:27 GMT+01:00 Przemysław Biecek <notifications@github.com>:
>
> > Good idea, but when?
> > Is is planned as a pre 2.0 feature?
> >
> >
> >
> > 2016-02-07 22:16 GMT+01:00 Marcin Kosiński <notifications@github.com>:
> >
> > > They are too long and can be created with the usage of Repository that
> is
> > > embed in the package
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/pbiecek/archivist/issues/210>.
> > >
> >
> >
> >
> > --
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pbiecek/archivist/issues/210#issuecomment-181121320
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/210#issuecomment-181122092>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
I've shortened few functions. You can also have a look at functions that I

- didn't move but are not so long
  - aoptions
  - asearch
  - cache
  - copyToRepo
  - getTags
  - setRepo

- shortened but one can look again at
  - loadFromRepo

- still long and didn't move
  - removeFromRepo

**Comment by pbiecek** [comment]
For copyToRepo, getTags, setRepo, loadFromRepo, removeFromRepo
I would export and use also *Local* or *Remote* versions.


2016-02-07 23:28 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> I've shortened few functions. You can also have a look at functions that I
>
>    -
>
>    didn't move but are not so long
>    - aoptions
>       - asearch
>       - cache
>       - copyToRepo
>       - getTags
>       - setRepo
>    -
>
>    shortened but one can look again at
>    - loadFromRepo
>    -
>
>    still long and didn't move
>    - removeFromRepo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/210#issuecomment-181135009>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
I Think loadFromRepo does not exist.
setRepo, copyToRepo, getTags are not exported

No idea what to do with removeFromRepo

2016-02-07 23:34 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
So I am waining for this one and will start #211

**Comment by pbiecek** [comment]
@MarcinKosinski deprecated functions, like createEmptyRepo() are in these long examples.

**Comment by MarcinKosinski** [comment]
Ok I understand. What do we do about `removeFromRepo` ? changing the name to `removeFromLocalRepo`?

**Comment by MarcinKosinski** [comment]
I have verified longer examples and removed deprecated names.
The only issue we have is with `rmFromRepo`. I'll change this here #218

**Comment by MarcinKosinski** [comment]
I've checked examples. Changed delete/create/rmFrom name convention to maintain consistency with Local/Remote function names. I also moved `dontrun` in few examples to make sure the package and examples work. I think examples are now run in about 80% of manual pages.

**Comment by pbiecek** [comment]
I will move rmFromRepo to rmFromLocalRepo.
The only question is, should the rmFromRepo be deprecated / non visible / just a copy
