### ISSUE TITLE
Final tests before upload to CRAN

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#211]
Check all function in the article before version 2.0 will be ready for CRAN

**Comment by MarcinKosinski** [comment]
+ I'd like to test whether my vignette for archivist.github works for archivist 2.0 before it's released to CRAN

**Comment by MarcinKosinski** [comment]
You can start checking.

**Comment by MarcinKosinski** [comment]
I've made all my tests.
I've got only one issue with #241

**Comment by MarcinKosinski** [comment]
Talking about the package. I can freeze him like it is right now.
