### ISSUE TITLE
Blog about addPrintToHook

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#213]
first: get 2.0 to CRAN

**Comment by pbiecek** [comment]
@MarcinKosinski I've prepared a short blog entry about addPrintToHook
It's here:
https://docs.google.com/document/d/13DT4resJ0RJ9vuBAKyDQZA4Fu11KyMht6xF2YKnnp3U/edit?usp=sharing

Feel free to change it, correct it, extend it if you wish.
I am planning to publish it on Tuesday

**Comment by MarcinKosinski** [comment]
Interesting. I've found few typos, so I'll Try to correct them 

Marcin Kosinski

Dnia 13.02.2016 o godz. 16:59 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by MarcinKosinski** [comment]
I've provided few linguistic changes.

**Comment by MarcinKosinski** [comment]
@pbiecek I've improved the documentation page of `addHooksToPrint` by passing a link to this blog post in the manual page 
https://github.com/pbiecek/archivist/commit/0add9801c13a1f25d423dd9d99546983e60d5766

and also I've changed naming convention from `Git` to `Remote` :)
