### ISSUE TITLE
%a% is not working

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#216]
> iris %a%
+ filter(Sepal.Length < 6) %a%
+ lm(Petal.Length~Species, data=.) %a%
+ summary() -> tmp
 Show Traceback
 
 Rerun with Debug
 Error in filter(`__LHS`, Sepal.Length < 6) : 
  object 'Sepal.Length' not found 
>

**Comment by pbiecek** [comment]
It was the problem with namespaces
should be dpyr::filter instead of filter
Fixed in the article

**Comment by MarcinKosinski** [comment]
Yes, I run on this many times :)
I think you just should add `library(dplyr)`. No need to write anything additional in the exmaple

**Comment by MarcinKosinski** [comment]
No warnings

````{R}
> ?ahistory
> createEmptyRepo("ahistory_check", default = TRUE)
Directory ahistory_check did not exist. Forced to create a new directory.
Warning message:
'createEmptyRepo' is deprecated.
Use 'createEmptyRepo is deprecated. Use createLocalRepo() instead.' instead.
See help("Deprecated") 
> aoptions("silent", TRUE)
[1] TRUE
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> iris %a%
+   filter(Sepal.Length < 6) %a%
+   lm(Petal.Length~Species, data=.) %a%
+   summary() -> artifact
> 
````

**Comment by pbiecek** [comment]
Good point, thanks
Authors of packages that use same function name like in base packages (filter / quantile) should ....
