### ISSUE TITLE
silent = TRUE by default?

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#217]
When using %a% I get a lot of warning messages (since session info is archived many times).

Maybe we can turn the silent=TRUE by default?

**Comment by pbiecek** [comment]
@MarcinKosinski what do you think about this?

**Comment by MarcinKosinski** [comment]
Good idea.

**Comment by pbiecek** [comment]
Done,
You have the token for changes.
I will add this to NEWS after you release the token.
