### ISSUE TITLE
saveToLocalRepo

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#219]
The only *Repo function without Local/remote is saveToRepo

Suggestion: Let's add saveToLocalRepo as a copy of saveToRepo.
Neither of them will be deprecated.

Other suggestion:
add asave()

**Comment by MarcinKosinski** [comment]
asave or archive :) I don't really like those long `*TypeRepo` names so `asave` sounds better than saveToLocalRepo

**Comment by pbiecek** [comment]
archive is cool, but then we will have collision with archivist.github.
I think that we shoud keep saveToLocalRepo, since some people may use it.
But shorter names are nicer so it is good to have both.


2016-02-09 13:43 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> asave or archive :) I don't really like those long *TypeRepo names so
> asave sounds better than saveToLocalRepo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/219#issuecomment-181848203>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
To sum up: 
We'll have 3 various names: `saveToRepo`, `saveToLocalRepo` and `asave`, as wrappers around saveToRepo.

**Comment by pbiecek** [comment]
Yes, but:
in the article I will write only about saveToLocalRepo
saveToRepo will be the exact copy of saveToLocalRepo, but will not be
'highlighted'

Should asave be the copy as well?


2016-02-09 14:16 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> To sum up:
> We'll have 3 various names: saveToRepo, saveToLocalRepo and asave, as
> wrappers around saveToRepo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/219#issuecomment-181858777>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Yes I think it's a good short and catchy convention

2016-02-09 14:23 GMT+01:00 Przemysław Biecek <notifications@github.com>:
