### ISSUE TITLE
List of function names for 2.0

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#220]
Current Table 1 looks like that:
https://www.dropbox.com/s/txr0y9zzorxokvn/Screen%20Shot%202016-02-08%20at%2017.06.16.png?dl=0

If anything should be changed, let's discuss it below

**Comment by MarcinKosinski** [comment]
Maybe text could be listed to right?

**Comment by pbiecek** [comment]
Is it like only numbers should be aligned o right?

**Comment by MarcinKosinski** [comment]
Maybe you are right. But we may deviate from this principle for this one
time, so that maybe this table would look better

2016-02-09 13:38 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
Here you have
https://www.dropbox.com/s/b5b7lppfrsfjsig/Screen%20Shot%202016-02-09%20at%2014.09.59.png?dl=0

imho the left aligned version is better
