### ISSUE TITLE
Submit v 2.0 to CRAN

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#222]
- check #211
- make sure that graphGallery is attached with proper artifacts
- change version to 2.0
- submit to CRAN
- set release on github to 2.0

**Comment by MarcinKosinski** [comment]
Could you please give me one more day. I think `saveToRepo` can be reimplemented in more professional way. #229  #228  #226  #227

**Comment by pbiecek** [comment]
sure, 
but let's finish it this week.

Changes in graphGallery broke CRAN version of archivist
https://cran.r-project.org/web/checks/check_results_archivist.html
we have 8 errors and I've already got a friendly warning that patch should arrive soon.
so we need to upload something to CRAN this week

**Comment by pbiecek** [comment]
so, token for changes is now in your hands

**Comment by MarcinKosinski** [comment]
You can be sure, that I'll check package today.
But I can't ensure you I won't find any bugs :)

I would be glad If we could submit new version on CRAN tomorrow.

2016-02-11 1:46 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
My last fixes are in #230

**Comment by MarcinKosinski** [comment]
Are we planning to add article as a vignette?

**Comment by pbiecek** [comment]
Likely, but maybe after it will be (hopefully) accepted?



2016-02-11 17:17 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Are we planning to add article as a vignette?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/222#issuecomment-182940025>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Agreed.

2016-02-11 17:38 GMT+01:00 Przemysław Biecek <notifications@github.com>:
