### ISSUE TITLE
repository in the root directory of archivsit repo

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#224]
Do we need archivist repository in the root directory of the github repo?

**Comment by pbiecek** [comment]
@MarcinKosinski do you know if we need archivist repo in the main directory of github archivist repo? 
It raises a note in check() so I would like to move it to the 'old' directory

**Comment by MarcinKosinski** [comment]
This repo in the root is for `Github` examples.
We can update examples that they would all work for `pbiecek/graphGallery`
repository or for
`pbiecek/archivist` subdir = 'graphGallery` (the one we attach for package).
After those updates we can remove the gallery from root :)


2016-02-10 2:39 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
Ok, let's not change anything that is not a bug ;-)

2016-02-10 11:31 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> This repo in the root is for `Github` examples.
> We can update examples that they would all work for `pbiecek/graphGallery`
> repository or for
> `pbiecek/archivist` subdir = 'graphGallery` (the one we attach for
> package).
> After those updates we can remove the gallery from root :)
>
>
> 2016-02-10 2:39 GMT+01:00 Przemysław Biecek <notifications@github.com>:
>
> > @MarcinKosinski <https://github.com/MarcinKosinski> do you know if we
> > need archivist repo in the main directory of github archivist repo?
> > It raises a note in check() so I would like to move it to the 'old'
> > directory
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pbiecek/archivist/issues/224#issuecomment-182162264
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/224#issuecomment-182301144>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek
