### ISSUE TITLE
rememberName & !(artifactName %in% ls(envir = parent.frame(1)))

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#227]
In first version of archivist we have a problem with `saveToRepo` function that it couldn't be used inside any other function because of environment issues that lead to situation in which we forgot about artifact's  name.

`saveToRepo` can be used inside another function and remember a nawet if we first assign an artifact in the environemnt in which the saveToRepo will be called like this:

````{R}
> tempfile() -> repoDir
> createLocalRepo(repoDir)
Directory /tmp/Rtmp1JuNNQ/fileaed7ec5f2a6 did not exist. Forced to create a new directory.
> archiveAr <- function(artifact, repoDir, artifactName = deparse(substitute(artifact))) {
+ 	assign(x = artifactName, value = artifact)
+ 	saveToRepo(artifact = artifact, repoDir = repoDir, artifactName = artifactName)
+ }
> data(iris)
> archiveAr(iris, repoDir = repoDir)
[1] "ff575c261c949d073b2895b05d1097c3"
> showLocalRepo(repoDir)
                           md5hash                             name         createdDate
1 ff575c261c949d073b2895b05d1097c3                             iris 2016-02-11 00:48:29
2 e5afb291fef752f68056e9393e5935ac e5afb291fef752f68056e9393e5935ac 2016-02-11 00:48:29

````

This is one workaround I would have to use in `archive` function to archive artifacts with their proper names. But what if this is done in more nested  situation? Than each time a user would have to `assign` artifact in every sub-nested function.

This is done due to the fact that we are checking for a name in the upper parent.frame here
rememberName & !(artifactName %in% ls(envir = parent.frame(1)))
and if this is there we archive artifact from the upper/parent environment save( file = file.path(repoDir,"gallery", paste0(md5hash, ".rda")), ascii = ascii, list = artifactName, envir = parent.frame(1))

This is problematic because to use `saveToRepo` in nested combinations one would have to assign artifact in every nested function/environment.

I have found a workaround for this that would make `saveToRepo` function more professional.  
We have a `technical` parameter `rememberName` that more-or-less ensures that we are in a nested call or not. If not then we probably will have a name. If we are in nested envir then we resign from knowing the name and artifact under the name that corresponds to it's md5hash

> rememberName	A logical value. Should not be changed by a user. It is a technical parameter.

This is such problematic parameter that I even got confused today with this issue https://github.com/pbiecek/archivist/issues/226 where the real problem is that:

`rememberName` is set to FALSE  ONLY THEN WHEN the saveToRepo is used in a nested envir during the archiving of data.

I think we can somehow remove those combinations (remove this technical parameter)
https://github.com/pbiecek/archivist/blob/master/R/saveToRepo.R#L212-223
and assign artifact in the `saveToRepo` function  like this

````{R}
> ls()
character(0)
> repoDir <- tempfile()
> createLocalRepo(repoDir = repoDir)
Directory /tmp/Rtmp1JuNNQ/fileaed6f0f0268 did not exist. Forced to create a new directory.
> iris345 <- iris
> exsave <- function(artifact, repoDir, ascii = TRUE, artifactName = deparse(substitute(artifact))) {
+ 	
+ 	md5hash <- digest::digest(artifact)
+ 	assign(x = artifactName, value = artifact)
+ 	save(file = file.path(repoDir, "gallery", paste0(md5hash,".rda")),
+ 			 ascii = ascii, list = artifactName)
+ 	return(md5hash)
+ }
> exsave(iris345, repoDir = repoDir) -> hash
> ls()
[1] "exsave"  "hash"    "iris345" "repoDir"
> rm(iris345)
> ls()
[1] "exsave"  "hash"    "repoDir"
> load(file.path(repoDir, "gallery", paste0(hash,".rda")))
> ls()
[1] "exsave"  "hash"    "iris345" "repoDir"
> swiss345 <- swiss
> # twice nested
> exsave_outer <- function(artifact, repoDir, ascii = TRUE, artifactName = deparse(substitute(artifact))) {
+ 	exsave(artifact, repoDir = repoDir, ascii = ascii, artifactName = artifactName)
+ }
> ls()
[1] "exsave"       "exsave_outer" "hash"         "iris345"      "repoDir"     
[6] "swiss345"    
> exsave_outer(swiss345, repoDir = repoDir) -> hash_outer
> ls()
[1] "exsave"       "exsave_outer" "hash"         "hash_outer"   "iris345"     
[6] "repoDir"      "swiss345"    
> rm(swiss345)
> load(file.path(repoDir, "gallery", paste0(hash_outer,".rda")))
> ls()
[1] "exsave"       "exsave_outer" "hash"         "hash_outer"   "iris345"     
[6] "repoDir"      "swiss345"    


````

**Comment by pbiecek** [comment]
Three options:
1. maybe we can use getAnywhere() which will locate the proper argument whatever it is.
2. We assume the the object is local (not nested) and do not support nested arguments (I do not like this one)
3. we will not store original names of artifacts (by default) thus by default there will be no problem.

**Comment by MarcinKosinski** [comment]
I'm not so sure about 3.
Names are the first thing I look at when  peeking at Tags.

Will elaborate more tomorrow.

2016-02-11 1:25 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
Ok we can now archive artifact under their given name. By default they are archived under their name (artifacName = deparse(substitute(artifact)). In a nested evaluation of `saveToRepo` user can specify the name of artifact under which he should be archived - so under `archivist.github::archive` and future wrappers for saveToRepo the function code will be clear.

Moreover move checking whether data was archived to `extractData` function.
What is more extractData uses saveToRepo in a nested way so we should specify md5hashes of datasets in this function (which is done #230 ) to maintain consistency that datasets are save under the name of it's md5hashes.

When #230  is merged we can close this issue
