### ISSUE TITLE
derivedTags = tags passed by attrs

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#228]
One day we invented a way of passing additional parameters by attrs of the artifact.
https://github.com/pbiecek/archivist/blob/master/R/saveToRepo.R#L240

But later we figure it out that one can pass additional tags during the archiving in `userTags` parameter. I think derviedTags are no longer needed and are confusing and they look ridiculous in the documentation 
here https://github.com/pbiecek/archivist/blob/master/R/saveToRepo.R#L82-L90
and here https://github.com/pbiecek/archivist/blob/master/R/Tags.R#L205-L213

**Comment by pbiecek** [comment]
I think they still can be useful. 

One situation: in the knitr report objects are automatically added to repo (addHooksToPrint), so we do not use the saveToRepo function directly and cannot add additional arguments.
But still we may wish to add some tag. 
So we can do this through attrs. Modify the object before it will be added to the repo

**Comment by MarcinKosinski** [comment]
This is the only situation it is usefull. Should we add such note to note
section of addHooksToPrint function?

2016-02-11 1:19 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
I do not think that such note is a muss, but if you think it could be useful.. feel free ;-)
