### ISSUE TITLE
getRemoteHook motivation

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#231]
What is the motivation for this function?
How can it help the user?
Maybe examples could be extended or in the description there can be some kind of motivation?

**Comment by pbiecek** [comment]
This function is used internally by other remote functions.
User shall not call this function directly. 
But user may overload this function and add support for other, non github/bitbucket repositories

**Comment by MarcinKosinski** [comment]
Is this function neccessary to be exported?

2016-02-11 21:23 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
It is described in the paper, maybe this is some argument?

But everything will work without this function being exported as well.


2016-02-11 21:31 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Is this function neccessary to be exported?
>
> 2016-02-11 21:23 GMT+01:00 Przemysław Biecek <notifications@github.com>:
>
> > This function is used internally by other remote functions.
> > User shall not call this function directly.
> > But user may overload this function and add support for other, non
> > github/bitbucket repositories
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pbiecek/archivist/issues/231#issuecomment-183048327
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/231#issuecomment-183050191>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment]
Ok, I've removed it from NAMESPACE
