### ISSUE TITLE
Do we still need the ascii parameter in saveToRepo?

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#232]
It was temporary fix for github, not it is not needed. What about removing it?

**Comment by pbiecek** [comment]
@MarcinKosinski what do you think about this?

**Comment by pbiecek** [comment]
Ok, it does not slow of complicate anything, so, let's keep it this way

**Comment by MarcinKosinski** [comment]
I think that different values of ascii TRUE/FALSE occure in various size of saved object

**Comment by pbiecek** [comment]
yes, but by default ascii = FALSE
and I do not see any reason why someone would like to choose ascii = TRUE

2016-02-11 22:51 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> I think that different values of ascii TRUE/FALSE occure in various size
> of saved object
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/232#issuecomment-183072660>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Me neither. So this might be removed?

2016-02-11 22:54 GMT+01:00 Przemysław Biecek <notifications@github.com>:
