### ISSUE TITLE
artifactName = NULL

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#233]
Currently for some objects, like sesion_info we call the digest() function two times. Before saveToRepo to get name of artifact and inside to calculate md5hash.

We may simplify it by supporting artifactName = NULL. In this case the once calculated md5hash is used as artifact name

**Comment by pbiecek** [comment]
extractData.* could be simplified with the option 'artifactName = NULL'
we could avoid almost all calls to digest() function

**Comment by MarcinKosinski** [comment]
I don't see this yet. Could you provide an example, or if faster, a fix commit?

**Comment by pbiecek** [comment]
It's here:
https://github.com/pbiecek/archivist/commit/04f3bb14f70749859324da6311854831db5ac628

btw: we've just hit 1000 commits

btw2: sorry for not waiting for response. It's minor thing so I've closed it and started tests

**Comment by MarcinKosinski** [comment]
1000 commits means that we are obliged to meet and celebrate :) and this
should be repeated after each thousand of commits

2016-02-11 22:52 GMT+01:00 Przemysław Biecek <notifications@github.com>:
