### ISSUE TITLE
serachInRepo, multiSearchInRepo

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#234]
Do you think we need both of those functions?
Maybe one could refactor searchinRepo to work it as simple searchInRepo and as multiSearchInRepo ?

**Comment by pbiecek** [comment]
multiSearchInLocalRepo will work for single patterns
so the searchinRepo is not needed
but I will keep it anyway, it has shorter name

2016-02-11 22:53 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Do you think we need both of those functions?
> Maybe one could refactor searchinRepo to work it as simple searchInRepo
> and as multiSearchInRepo ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/234>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment]
suggestion: do not change

**Comment by MarcinKosinski** [comment]
suggestion
multiSearchInLocal/RemoteRepo will have new name "searchInLocal/RemoteRepo"
old searchInLocal/RemoteRepo will not be exported

**Comment by pbiecek** [comment]
isn't too big change?
it will affect article and tests

and in most cases I think people will use just one pattern

**Comment by MarcinKosinski** [comment]
Last shot:

- extend searchInLocal/RemoteRepo functionality to work as multiSearch but in such way that it will not broke it's previous functionality (i.e. new parameter multi = TRUE can trigger multiSearch)
- update examples in documentation
- remove multiSearch from article

I can volunteer

**Comment by pbiecek** [comment]
ok,
let me finish #235,
and then you can remove multiSearch

**Comment by MarcinKosinski** [comment]
sure

**Comment by pbiecek** [comment]
ok, #235 is ready
please check if  after changes:
* check() is passing
* tests() is passing
* demo() is passing
* replicationScript() is passing

results in replicationScript are same as in article

**Comment by MarcinKosinski** [comment]
Ok I have finished reading article. I have few improvements and suggestions.
I've also fixed a code in few places, so I'll change the replicationScript also.
I'll send you notes after I'll close this issue.

**Comment by MarcinKosinski** [comment]
Check and tests work.
There is an issue with demo and replication script but this not my fault.
#241 

Now if  `length(pattern) > 1 & is.character(pattern)` then the multi Version is used.
