### ISSUE TITLE
realDBname in searchInLocalRepo

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#235]
As stated in documentation

> realDBname A logical value. Should not be changed by user. It is a technical parameter.

I am wondering whether we are smarter after those 2 years of development and can somehow omit this parameter?

**Comment by pbiecek** [comment]
I would change downloadDB()
in a way to create there a temporary directory and save there backpack.db
inside.
Then there will be no reason for distinguishing real db and not real

2016-02-11 22:54 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> As stated in documentation
>
> realDBname A logical value. Should not be changed by user. It is a
> technical parameter.
>
> I am wondering whether we are smarter after those 2 years of development
> and can somehow omit this parameter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/235>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment]
ok, checklist:
* check() passed
* tests() passed
* replicationScript() passed

**Comment by MarcinKosinski** [comment]
hats off :)
