### ISSUE TITLE
do we need parametrizeRepo in this version?

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#236]

**Comment by MarcinKosinski** [comment]
I think we don't. It's only in devel folder and probably will be used in the future `archivist.S4` package, (if such will be created :))

**Comment by pbiecek** [comment]
would you move it to 'old' dir or to 'archivist2' repo ?

2016-02-11 23:46 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> I think we don't. It's only in devel folder and probably will be used in
> the future archivist.S4 package, (if such will be created :))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/236#issuecomment-183090013>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
fix with https://github.com/pbiecek/archivist/commit/923e28d316a3d8c579366f39666bc6aa3d0a1c70
