### ISSUE TITLE
archivist.shiny / shinySearchInRemoteRepo

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#237]
Would it be possible to improve shinySearchInLocalRepo to provide somehow similiar functionality but for remote repos? One could download whole repo, then unzip it and use shinySearchInLocal for downloaded repository.

This is only a question. It can be added to other package, future versions.

**Comment by pbiecek** [comment]
will vote for other package, i.e. archivist.shiny.
Let's freeze archivist

**Comment by MarcinKosinski** [comment]
It can be reopend if one decides to create a new package or additional function.

**Comment by MarcinKosinski** [comment]
Moved to  https://github.com/pbiecek/archivist/issues/266
