### ISSUE TITLE
archivist.cache / %cache% / aoptions('cache_evaluation', TRUE)

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#238]
Would it be beneficial for human kind to create %cache% operator that would be a mix of cache+%a% or a special package in which %a% would work as %cache% or every call would be cached? Or maybe we could set option: aoptions('cache_evaluation', TRUE) to globally change each evaluation to be used with 'cache' function?

**Comment by pbiecek** [comment]
Sounds really really good
but let's move it to archivist.cache package
and let's freeze archivist

**Comment by MarcinKosinski** [comment]
It can be reopened if one decides to create a new package or additional function.
