### ISSUE TITLE
repoDir = NULL / repoDir = aoptions('repoDir')

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#239]
I have found that in `searchInLocalRepo` by default the repoDir have been changed to `aoptions('repoDir')` so we do not need such line in the documentation:
https://github.com/pbiecek/archivist/blob/master/R/searchInRepo.R#L42

because if it is specified to NULL then in `checkDirectory` we takes globally set Repository https://github.com/pbiecek/archivist/blob/master/R/createEmptyRepo.R#L170-L173

I would not mind and removed above note from documentation and would remove `is.null` check from this `stopifnot` https://github.com/pbiecek/archivist/blob/master/R/searchInRepo.R#L123 but I think this should be a global convention for whole package.

For now loadFromLocalRepo has `repoDir = NULL` so we would have to be consistent.

Propositions:

- Remove such lines from all documentation man pages: https://github.com/pbiecek/archivist/blob/master/R/searchInRepo.R#L42
- change `repoDir` argument to `aoptions("repoDir")` in all functions beside `createLocalRepo` and `delereLocalRepo`

**Comment by MarcinKosinski** [comment]
Also such notes are obsolete #https://github.com/pbiecek/archivist/blob/master/R/searchInRepo.R#L64-L65

**Comment by pbiecek** [comment]
My intention was to use aoptions() for all repoDir's
So for loadFromLocalRepo(), I've just overlooked it


2016-02-12 0:46 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Also such notes are obsolete #
> https://github.com/pbiecek/archivist/blob/master/R/searchInRepo.R#L64-L65
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/239#issuecomment-183112798>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Ok. I'll take that.

**Comment by MarcinKosinski** [comment]
done

**Comment by pbiecek** [comment]
shall we close the issue?

**Comment by MarcinKosinski** [comment]
It is closed for over 10 hours. It's done :)

**Comment by pbiecek** [comment]
thanks!

2016-02-12 13:03 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> It is closed for over 10 hours. It's done :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/239#issuecomment-183296565>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek
