### ISSUE TITLE
Does asearch work only for GitHub repositories?

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#240]

**Comment by MarcinKosinski** [comment]
In the last commit, I've changed the man page or this function beacuse I thought it should work for Remote not only GitHub repositories. Shoulg it work for all Remote repos? So there should be an additional `repoType` parameter that is passed to `multisearch - > search in a while`

**Comment by pbiecek** [comment]
repoType is passed only through aoptions("repoType")
asearch() will work for bitbucket
but first user need to set 
aoptions("repoType", "bitbucket")

I would not extend aseach() formula from current user/repo/subdir/md5hash

**Comment by MarcinKosinski** [comment]
Ok so the changes in documentation where needed.
I've added additional parameter `repoType` but we can undo this commit https://github.com/pbiecek/archivist/commit/e186a3274f34b1c613a405421656f9cf22f05f78

**Comment by pbiecek** [comment]
vote for undo. 
(otherwise same issue with aread, asession, aformat).

**Comment by MarcinKosinski** [comment]
Ok, I'll undo
