### ISSUE TITLE
multiSearch - removed or deprecated?

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#242]
In NEWS there is an information that multiSearch is deprecated.
But actually it's removed.
I will make it deprecated (as in the NEWS.md file)

**Comment by MarcinKosinski** [comment]
Ok, sorry. You are write. I am always removing function instead of moving them to deprecations.

**Comment by pbiecek** [comment]
Ok, I will add multiSearch as deprecated (just in case that someone is using it)

**Comment by MarcinKosinski** [comment]
Ok

Marcin Kosinski

Dnia 12.02.2016 o godz. 18:44 Przemysław Biecek <notifications@github.com> napisał(a):
