### ISSUE TITLE
obsolete archiwum.png file

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#244]
There are obsolete names of functions. We can think about new image :)

**Comment by pbiecek** [comment]
Working on https://raw.githubusercontent.com/pbiecek/archivist/master/archiwum2.png
comments welcome.
Not all functions are there because I wish to keep it simply.
Still I am not 100% happy with it

**Comment by MarcinKosinski** [comment]
Looks good since I could add one more Column 'write remove' for archivist.github in the future.

Maybe there should be 'R/H' convention in shortcuts instead of 'RH'

Marcin Kosinski

Dnia 26.06.2016 o godz. 17:56 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by MarcinKosinski** [comment]
You can add 'asave' to shortcuts

Marcin Kosinski

Dnia 26.06.2016 o godz. 17:56 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by MarcinKosinski** [comment]
And there is also showRepo that could be added under summaryRepo

Marcin Kosinski

Dnia 26.06.2016 o godz. 17:56 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
added
