### ISSUE TITLE
Current tests verify strange things

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#245]
Current tests will fail after any more serious change in pbiecek/graphGallery.

Sometimes they check if the size of repository is exactly 8x3 and they report error is it's 9x3 (because of additional session info).

It's not good, because I cannot remove wrong objects from this repository (e.g. old ggplot2 objects) or add new without risking that archivist on CRAN will generate a lot of errors during check().

We need tests that are more robust when it comes to ,,external'' repositories.

It's not urgent, but some day it should be cleaned.

**Comment by MarcinKosinski** [comment]
Sure. Good point.

**Comment by MarcinKosinski** [comment]
Have you changed testes for version `2.0.1` and one might close this issue?

**Comment by pbiecek** [comment]
No, I have not touch tests yet.


2016-02-26 16:55 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Have you changed testes for version 2.0.1 and one might close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/245#issuecomment-189337021>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment]
I have no idea how to change these tests, 
but maybe it's good that there are too specific, they will detect any possible problem with related packages
so I am closing this issue
