### ISSUE TITLE
Blog about tracing of all results of lm function

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#246]
This is super cool. You can use 'trace()' function to execute any command after specific function. So for example these lines:

library(archivist)
setLocalRepo("arepo")
trace(lm, exit = quote(saveToLocalRepo(z)))

will save all results of all calls to lm() function to the repository

**Comment by MarcinKosinski** [comment]
````{R}
atrace <- function(function_name, repoDir) {
   trace(function_name, exit = quote(asve(z, repoDir))
}
````

This could be mixed with the 

> When one is interested in all objects of class lm that were created with Species explanatory variable (with versicolor factor level) in pbiecek/graphGallery repository, then one might download them, extract R-squared statistics and coefficients, bind them in one data frame and sort rows by R-squared statistics to get the best model with the following code
````{R}
asearch(patterns = c('class:lm',
                            'coefname:Speciesversicolor'),
                repo = 'pbiecek/graphGallery') %>%
    # download all matching objects in a list
    lapply(function(x) {
        c(r.squared = summary(x)$r.squared,
                    x$coef) %>%
            # extract coeffs and R-squared statistic
            t %>%
            as.data.frame # transpose for binding
        }) %>% 
    do.call(dplyr::bind_rows, .) %>% # apply bind_rows to all list elements
    arrange(r.squared) # arrange rows by r.squared
````
> This might be used to extract the most valuable model (in terms of R-squared statistics) within the Repository. Imagine a Repository with hundreds of classification models and their potentional blends, where each of them is archived with additional Tags describing their performance. One gained a great tool to search for the best classifier within dozens of models

**Comment by MarcinKosinski** [comment]
I'm amazed again.

**Comment by pbiecek** [comment]
This version of atrace will not work for all functions, since only in 'lm()' the results is named 'z'. In other functions it can have different names. 

But the example that you gave is cool, and now you can also add md5 hash of the model

mm <- asearch(patterns = c('class:lm',
                     'coefname:Speciesversicolor'),
        repo = 'pbiecek/graphGallery')

mm %>%
  lapply(function(x) {
    c(r.squared = summary(x)$r.squared,
      x$coef) %>%
      # extract coeffs and R-squared statistic
      t %>%
      as.data.frame # transpose for binding
  }) %>% 
  do.call(dplyr::bind_rows, .) %>% # apply bind_rows to all list elements
  cbind(data.frame(md5hash = names(mm))) %>%
  arrange(r.squared) %>% # arrange rows by r.squared
    unique()

**Comment by MarcinKosinski** [comment]
Beautifull.
It's an example from `archivist.github` vignette but in blog about
archivist.github I think I won't show this exmaple so feel free.

If there is an automated way of extracing the names of function results,
then this could be doable for broader classes.

2016-02-14 0:00 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
cool,
actually the .Last.value may be used (after possible some changes in eva())

2016-02-14 0:13 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Beautifull.
> It's an example from `archivist.github` vignette but in blog about
> archivist.github I think I won't show this exmaple so feel free.
>
> If there is an automated way of extracing the names of function results,
> then this could be doable for broader classes.
>
> 2016-02-14 0:00 GMT+01:00 Przemysław Biecek <notifications@github.com>:
>
> > This version of atrace will not work for all functions, since only in
> > 'lm()' the results is named 'z'. In other functions it can have different
> > names.
> >
> > But the example that you gave is cool, and now you can also add md5 hash
> > of the model
> >
> > mm <- asearch(patterns = c('class:lm',
> > 'coefname:Speciesversicolor'),
> > repo = 'pbiecek/graphGallery')
> >
> > mm %>%
> > lapply(function(x) {
> > c(r.squared = summary(x)$r.squared,
> > x$coef) %>%
> > # extract coeffs and R-squared statistic
> > t %>%
> > as.data.frame # transpose for binding
> > }) %>%
> > do.call(dplyr::bind_rows, .) %>% # apply bind_rows to all list elements
> > cbind(data.frame(md5hash = names(mm))) %>%
> > arrange(r.squared) %>% # arrange rows by r.squared
> > unique()
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pbiecek/archivist/issues/246#issuecomment-183769741
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/246#issuecomment-183770356>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment]
I am goint to publish this tomorrow:

Let’s see how to collect all linear regression models that you will ever create.

It’s easy with the trace() function. A really powerful, yet not that popular function, that allows you to inject any R code in any point of body of any function.
Very useful in debugging but have also other interesting applications.
Below I will show how to use this function to store a copy of every linear model that is created. In the same way you may store copies of plots/other models/data frames/anything.

To store persistent copy of an object one can simply use a save() function. But we are going to use the archivist package instead. It stores objects in a repository and give you some nice features, like searching within repository, sharing the repository with other users, checking session info for a particular object or restoring packages to versions consistent with a selected object.

To use archivist with the trace() function you just need to call two lines. First one will create an empty repo, and the second will execute ‘saveToLocalRepo()’ at the end of each call to the lm() function.


# create an empty repo
createLocalRepo ("allModels", default = TRUE)
# add tracing code
trace(lm, exit = quote(saveToRepo(z)))
# create an empty repo
createLocalRepo ("allModels", default = TRUE)
# add tracing code
trace(lm, exit = quote(saveToRepo(z)))
Now, at the end of every lm() function the fitted model will be stored in the repository.
Let’s see this in action.


> lm(Sepal.Length~., data=iris) -> m1
Tracing lm(Sepal.Length ~ ., data = iris) on exit 

> lm(Sepal.Length~ Petal.Length, data=iris) -> m1
Tracing lm(Sepal.Length ~ Petal.Length, data = iris) on exit 

> lm(Sepal.Length~-Species, data=iris) -> m1
Tracing lm(Sepal.Length ~ -Species, data = iris) on exit
> lm(Sepal.Length~., data=iris) -> m1
Tracing lm(Sepal.Length ~ ., data = iris) on exit 
 
> lm(Sepal.Length~ Petal.Length, data=iris) -> m1
Tracing lm(Sepal.Length ~ Petal.Length, data = iris) on exit 
 
> lm(Sepal.Length~-Species, data=iris) -> m1
Tracing lm(Sepal.Length ~ -Species, data = iris) on exit
All models are stored as rda files in a disk based repository.
You can load them to R with the asearch() function.
Let’s get all lm objects, apply the AIC function to each of them and sort along AIC.


> asearch("class:lm") %>% 
    sapply(., AIC) %>% 
    sort
4c3ae060f3aaa2509b2faf63d857358e 5c5751e36b31b2251d2767d96993320a 
                        79.11602                        160.04042 
ed2f4d257fd568c5c6f231fadc7aa645 
                       372.07953
> asearch("class:lm") %>% 
    sapply(., AIC) %>% 
    sort
4c3ae060f3aaa2509b2faf63d857358e 5c5751e36b31b2251d2767d96993320a 
                        79.11602                        160.04042 
ed2f4d257fd568c5c6f231fadc7aa645 
                       372.07953
The aread() function will download the selected model.


> aread("4c3ae060f3aaa2509b2faf63d857358e")

Call:
lm(formula = Sepal.Length ~ ., data = iris)

Coefficients:
      (Intercept)        Sepal.Width       Petal.Length        Petal.Width  
           2.1713             0.4959             0.8292            -0.3152  
Speciesversicolor   Speciesvirginica  
          -0.7236            -1.0235 
> aread("4c3ae060f3aaa2509b2faf63d857358e")
 
Call:
lm(formula = Sepal.Length ~ ., data = iris)
 
Coefficients:
      (Intercept)        Sepal.Width       Petal.Length        Petal.Width  
           2.1713             0.4959             0.8292            -0.3152  
Speciesversicolor   Speciesvirginica  
          -0.7236            -1.0235 
Now you can just create model after model and if needed they all can be restored.

Read more about the archivist here: http://pbiecek.github.io/archivist/.

**Comment by MarcinKosinski** [comment]
I have just realized that you posted a comment here (I'm on a short holiday at the seaside). It looks fine :) Maybe there should be one additional sentence to the summary after `Now you can just create model after model and if needed they all can be restored` - maybe it would be good to mention that they also can be TAGGED and that TAGS enables easier management of searching and restoring :)

http://smarterpoland.pl/index.php/2016/05/all-your-models-belong-to-us-how-to-combine-package-archivist-and-function-trace/

**Comment by MarcinKosinski** [comment]
Updated `Posts` section on `pbiecek.github.io/archivist/` with this blog post :)
https://github.com/pbiecek/archivist/commit/ae79359e31ef3be79df23c44b51a37b55c525698
