### ISSUE TITLE
please warn others of changes to archivist

### ISSUE THREAD

**Issue by achubaty** [pbiecek/archivist#247]
With the release of v2.0 on CRAN, our packages that depend on `archivist` have broken due to the non-backwards compatible changes made in `archivist`. We are updating our packages accordingly, but these types of changes take time to get ready for CRAN.

In the future, please follow Hadley Wickham's recommendations at http://r-pkgs.had.co.nz/release.html by doing the following:

1. Do not immediately deprecate functions. A 'soft deprecation' where the user is warned (via `.Deprecated()` of the change is preferred so that the package maintains backward compatibility with older code.
2. Please check reverse dependencies (http://r-pkgs.had.co.nz/release.html#release-deps) and contact the package maintainers where appropriate to inform them of upcoming changes. Hadley always gives package maintainers 2 weeks' notice before submitting package updates to CRAN, which is usually sufficient time to make any changes and resubmit if there are any problems.

Thank you.

**Comment by pbiecek** [comment]
@achubaty 
Sorry for this rush. We were so focussed on closing all issues for version 2.0 (and version 1.9 have not reach CRAN), and we were so convinced that these changes are better, that we have forgotten about making the change smoother.

I hope that changes in archivist 2.0 do not create too much trouble for you.

If you can list methods that break compatibility with SpaDES we will be happy to either 1) suggest how to update SpaDES or 2) we will submit an path for archivist to make it still compatible with SpaDES.

Again, sorry for causing these troubles.

**Comment by achubaty** [comment]
Fortunately, it was easy for me to debug -- your NEWS.md file listed the changes you made so it was simply a matter of doing a find/replace -- but for a non-developer they will be confused why there previously working code suddenly doesn't work. The message R gives is about "the function not being exported by the package", which doesn't help an ordinary user figure out what's wrong, hence a message via `.Deprecated()` is preferred.

**Comment by achubaty** [comment]
I might still recommend a patch submission to CRAN that more gracefully handles the deprecation issue.

**Comment by pbiecek** [comment]
@achubaty we will upload the patch. Would you list functions that you found missing? 
Are they local or remote functions?

@MarcinKosinski do you remember which functions got removed?
I found deleteRepo() but maybe there are also others.

I would not add *Github* functions (unless it's not really needed)

**Comment by achubaty** [comment]
Only the removal of `rmFromRepo` affected SpaDES, but from your NEWS file there are a few others you removed:

> For the above reason `deleteRepo` was deprecated. Use `deleteLocalRepo`
> For the above reason `createEmptyLocalRepo` and `createEmptyRepo` were deprecated. Use `createLocalRepo`.
> For the above reason `rmFromRepo` was deprecated. `Use rmFromLocalRepo`

**Comment by MarcinKosinski** [comment]
Yes, those are all.

deleteRepo from 1.8 is now deleteLocalRepo
rmFromRepo from 1.8 is now rmFroLocalRepo
+ multiSearchIn*Repo are now merged with regular searchIn*Repo

2016-02-15 23:12 GMT+01:00 Alex Chubaty <notifications@github.com>:

**Comment by pbiecek** [comment]
Version 2.0.1 gets CRAN. rmFromLocalRepo and other functions are available there (but marked as deprecated)
