### ISSUE TITLE
osoblete options in zzz.R

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#248]
there are few predifined values of `aoptions` that can be set in `archivist.github` and do not need to be specified in `zzz.R` in `.onLoad` secition such us:

- https://github.com/pbiecek/archivist/blob/master/R/zzz.R#L12
- https://github.com/pbiecek/archivist/blob/master/R/zzz.R#L4
- https://github.com/pbiecek/archivist/blob/master/R/zzz.R#L15-L17
- https://github.com/pbiecek/archivist/blob/master/R/zzz.R#L15-L17
- https://github.com/pbiecek/archivist/blob/master/R/zzz.R#L18
- https://github.com/pbiecek/archivist/blob/master/R/zzz.R#L21

What is more, this is no longer needed parameter:
- https://github.com/pbiecek/archivist/blob/master/R/zzz.R#L14

**Comment by pbiecek** [comment]
Right,
will you change it? (I can do this as well)
It may be submittet as 2.0.1 along with deprecated functions.

**Comment by MarcinKosinski** [comment]
Removed
