### ISSUE TITLE
createMDGallery lines parameter

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#249]
There are sometimes situations in which user would like to use `addTags=TRUE` but the output is very long since artifacts have +20k tags (varname in case o `RTCGA::BRCA.rnaseq`). Would it be alright to provide additional parameter `maxTags = 100` which would be responsible for the lenght of each chunk with Tags information?

**Comment by MarcinKosinski** [comment]
I've seen you referenced this issue 5 days ago. Have you considered this functionality?

**Comment by MarcinKosinski** [comment]
@pbiecek

**Comment by pbiecek** [comment]
Yes, it looks like good idea.
An alternative solution is to have a textarea with fixed height, then all
tags will be on page but will use only fixed amount of space (rest will be
scrollable)


2016-02-26 16:54 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> @pbiecek <https://github.com/pbiecek>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/249#issuecomment-189336654>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Do you think it's doable in rmarkdown?

2016-02-26 17:51 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
in markdown yes, but not in github markdown
Ok, so let's add the limit maxTags argument

2016-02-26 18:28 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Do you think it's doable in rmarkdown?
>
> 2016-02-26 17:51 GMT+01:00 Przemysław Biecek <notifications@github.com>:
>
> > Yes, it looks like good idea.
> > An alternative solution is to have a textarea with fixed height, then all
> > tags will be on page but will use only fixed amount of space (rest will
> be
> > scrollable)
> >
> >
> > 2016-02-26 16:54 GMT+01:00 Marcin Kosiński <notifications@github.com>:
> >
> > > @pbiecek <https://github.com/pbiecek>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/pbiecek/archivist/issues/249#issuecomment-189336654
> > >.
> > >
> >
> >
> >
> > --
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pbiecek/archivist/issues/249#issuecomment-189367827
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/249#issuecomment-189382651>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
It's very frustrating that there appears so many various disyributions. In jekyll-knitr-hydrze regular markdown links does not work :)

Marcin Kosinski

Dnia 26.02.2016 o godz. 19:05 Przemysław Biecek <notifications@github.com> napisał(a):
