### ISSUE TITLE
current DOI

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#253]
@pbiecek in README.md we are linking to such DOI https://zenodo.org/record/31445#.VszUc5eDhz0

Do we have newer one?

**Comment by MarcinKosinski** [comment]
again in #267

**Comment by pbiecek** [comment]
updated in daf4189e00305f5b430328590850ff3e76ddd2ae

2016-05-30 12:46 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> again in #267 <https://github.com/pbiecek/archivist/issues/267>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/pbiecek/archivist/issues/253#issuecomment-222465880>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEaPvnN6rR9yRpIluZazsJq8UAUzha5Iks5qGr_ygaJpZM4HhFUD>
> .
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek
