### ISSUE TITLE
Disqus for archivist

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#256]
according to #192 I was trying to synchronize `Disqus` for archivist package but there appears to be such a chanel already http://pbiecek.github.io/archivist/2015/12/12/sample-post.html

Should we create some kind of workaround `rarchivist` / `archivistR` chanel?

**Comment by pbiecek** [comment]
Good idea,
or archivist_package or archivist_r

2016-02-26 16:49 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> according to #192 <https://github.com/pbiecek/archivist/issues/192> I was
> trying to synchronize Disqus for archivist package but there appears to
> be such a chanel already
> http://pbiecek.github.io/archivist/2015/12/12/sample-post.html
>
> Should we create some kind of workaround rarchivist / archivistR chanel?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/256>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek
