### ISSUE TITLE
archivist status

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#258]
@pbiecek should we change our status in `README.md` from `active` to `inactive`

> Active – The project has reached a stable, usable state and is being actively developed.
Inactive – The project has reached a stable, usable state but is no longer being actively developed; support/maintenance will be provided as time allows.
http://www.repostatus.org/

**Comment by pbiecek** [comment]
I am not convinced, it's so close to 'Unsupported'.

Let's give it a transition period, let's say 6 months (actually the eRum
might be a good deadline).
If nothing will change, then let's make it inactive.

I do not have plans for any new functionalities in this package,
and I think it's mature right now
but let's not close it too fast.
Who know, maybe something will emerge (like these problems with ggplot2 v
2.1.0)



2016-03-22 10:16 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> @pbiecek <https://github.com/pbiecek> should we change our status in
> README.md from active to inactive
>
> Active – The project has reached a stable, usable state and is being
> actively developed.
> Inactive – The project has reached a stable, usable state but is no longer
> being actively developed; support/maintenance will be provided as time
> allows.
> http://www.repostatus.org/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/258>
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Ok, so we'll get back to this after eRum.
I am only planning to post about archivist.github [which this post will be finished today].
