### ISSUE TITLE
add staticdocs to website

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#265]

**Comment by MarcinKosinski** [comment]
@pbiecek @wchodor 
I'm happy to announce that archivist has now have `Static Docs` : http://pbiecek.github.io/archivist/staticdocs/
that are available from sidebar in the main page http://pbiecek.github.io/archivist

**Comment by pbiecek** [comment]
Well done!


2016-04-25 19:24 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> @pbiecek <https://github.com/pbiecek> @wchodor
> <https://github.com/wchodor>
> I'm happy to announce that archivist has now have Static Docs :
> http://pbiecek.github.io/archivist/staticdocs/
> that are available from sidebar in the main page
> http://pbiecek.github.io/archivist
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/265#issuecomment-214449641>
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by wchodor** [comment]
Great!
