### ISSUE TITLE
Integration of shiny and archivist

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#266]
An idea:
enhanced plotOutput() that 1. add each plot to archivist repository (at least each ggplot2 plot) 2. creates a link to this object in repository 3. add small footnote with aread() instruction.

I was plying with this concept a bit and it turns to be quite useful. Imagine that by changing shiny inputs you have found interesting result and now you would like to access to this object. It might be easy with archivst.

**Comment by MarcinKosinski** [comment]
Would you rather create `archivist.shiny` package as an extension of archivist? It can have `archivist` in depends? I haven't noticed that earlier because we do not have Email-service

Could you be so kind and create e-mail notification for this repository?
Settings -> Webhooks & services -> Add Service -> Email -> and paste0 mine gmail address?

I think it's an interesting improvement of `archivist` concept

**Comment by MarcinKosinski** [comment]
#237

**Comment by pbiecek** [comment]
I've added your email as a service, but as collaborator you should be able
to do this yourself as well.

Initially I thought that this feature may be implemented as a single
function as addHooksToPrint(),
but I see your point and agree that it should be a new add-on package.




2016-05-30 12:45 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> #237 <https://github.com/pbiecek/archivist/issues/237>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pbiecek/archivist/issues/266#issuecomment-222465723>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEaPvt8JoZHJVp9iHuh0z86UwL90v8Xbks5qGr_EgaJpZM4Ikjci>
> .
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
I have no rights to click Settings as I don't see such Button

![archivist_settings](https://cloud.githubusercontent.com/assets/6773454/15652054/d3fe16e4-2683-11e6-80cb-0f43a7850010.png)

I am not 100% convinced that new package is the right way to do this. If this is just one function then it can be implemented in archivist 2.0.5/2.1.0 ?

**Comment by MarcinKosinski** [comment]
Have You considered implementing this feature? Susan Holmes has agreed during her talk that there is a huge demand of making interactive data exploration with shiny more reproducible :)

**Comment by pbiecek** [comment]
I have some ultra alpha version, will show this during the useR
but maybe I should blog about this as well

2016-06-25 19:06 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> Have You considered implementing this feature? Susan Holmes has agreed
> during her talk that there is a huge demand of making interactive data
> exploration with shiny more reproducible :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pbiecek/archivist/issues/266#issuecomment-228558496>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEaPvpqoRW5svj6VxRs6QxDGp_I9lkvEks5qPWALgaJpZM4Ikjci>
> .
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment]
with #274 now one can aread() asession() and asearch() from URL repository.
should be enough to work with shiny apps
