### ISSUE TITLE
obsolete DOI

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#267]
We have such link in readme.md to DOI https://zenodo.org/record/46016#.V0wS5J4U5Qs is readme.md obsolete or we do not have newer DOI for 2.0.4? @pbiecek

**Comment by pbiecek** [comment]
I've uploaded the 2.0.4
here it will be:
https://zenodo.org/record/53774

After the upload will be completed I will update the link

2016-05-30 12:20 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> Assigned #267 <https://github.com/pbiecek/archivist/issues/267> to
> @pbiecek <https://github.com/pbiecek>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pbiecek/archivist/issues/267#event-675890619>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEaPvgIgXzaYK_b3IuDUBGt28J-b5H4xks5qGroJgaJpZM4IprJ3>
> .
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
close with https://github.com/pbiecek/archivist/commit/daf4189e00305f5b430328590850ff3e76ddd2ae
