### ISSUE TITLE
addHookToPrint for latex documents also

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#270]
@pbiecek `alink` function in addHooksToPrint can take `format` parameter.
What do you think about adding new `format` parameter to `addHooksToPrint` that could be passed to `alink` https://github.com/pbiecek/archivist/blob/master/R/alink.R#L32
?

**Comment by pbiecek** [comment]
Good idea!

2016-06-08 17:02 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> @pbiecek <https://github.com/pbiecek> alink function in addHooksToPrint
> can take format parameter.
> What do you think about adding new format parameter to addHooksToPrint
> that could be passed to alink
> https://github.com/pbiecek/archivist/blob/master/R/alink.R#L32
> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pbiecek/archivist/issues/270>, or mute the thread
> <https://github.com/notifications/unsubscribe/AEaPvpspYdWYH-KMped1TRdPVTDGsuDJks5qJtmQgaJpZM4IxD0G>
> .
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Done, and news are updated
