### ISSUE TITLE
not proper check in addHooksToPrint

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#271]
suppose a user passes `class=c('ggplot', 'asdasd', 'data.frame')` to `addHooksToPrint

this check

https://github.com/pbiecek/archivist/blob/master/R/addArchivistHooks.R#L65

will add hooks for ggplots and will break for `asdasd` and will not add hooks for `data.frames` perhaps this should be checked before `for` loop and should break if one class has no print and shouldn't provide hooks for any class since such behaviour might be safer? @pbiecek

**Comment by pbiecek** [comment]
So currently, if this is called in knitr, then the knitting is stopped but
global environment is not affected.
So imho it does not matter if we do the ceck before the loop.

We can change this behaviour and generate warning instead of stop (if there
is no suitable print function then we can skip this class with warning).


2016-06-08 17:28 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> suppose a user passes class=c('ggplot', 'asdasd', 'data.frame') to
> `addHooksToPrint
>
> this check
>
> https://github.com/pbiecek/archivist/blob/master/R/addArchivistHooks.R#L65
>
> will add hooks for ggplots and will break for asdasd and will not add
> hooks for data.frames perhaps this should be checked before for loop and
> should break if one class has no print and shouldn't provide hooks for any
> class since such behaviour might be safer? @pbiecek
> <https://github.com/pbiecek>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pbiecek/archivist/issues/271>, or mute the thread
> <https://github.com/notifications/unsubscribe/AEaPvji7ZL9uFPG0XclmDfGbMx1nFsRcks5qJt-fgaJpZM4IxFqR>
> .
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
you can set knitr to compile file even if there are warnings and errors (that's how Sweave is set by default)

**Comment by pbiecek** [comment]
fixed in d74dfeb6493dd6e93766a55038a45d5eedeb4941
first, all classes are check, 
if there are no errors then consecutive print() functions are being overloaded

**Comment by MarcinKosinski** [comment]
Thanks!

Marcin Kosinski

Dnia 11.07.2016 o godz. 23:36 Przemysław Biecek <notifications@github.com> napisał(a):
