### ISSUE TITLE
URL as repoDir

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#274]
Would archivist functions for reading and searching work for repoDir which is an URL path not a local directory?

It will be very useful for shiny applications (there repos are accessible through URLs),
but I am not sure if every read-only function is able to deal with URLs

**Comment by pbiecek** [comment]
It looks like the only problem is the 'checkDirectory(repoDir)' function which do not expect URLs

**Comment by pbiecek** [comment]
This code may be used for testing
 aoptions("repoDir", "http://mi2.mini.pw.edu.pl:8080/archivist/arepo")
 asearch("class:gg")

**Comment by pbiecek** [comment]
url.exist was not working properly, so I've added own url.dont.exists

**Comment by pbiecek** [comment]
aread() is working
asearch() not jet

**Comment by pbiecek** [comment]
let's allow aread() to understand the full url, e.g.
archivist::aread('http://mi2.mini.pw.edu.pl:8080/archivist/arepo/3e98a38e82f76bcf2add5aae37b99b25')

**Comment by MarcinKosinski** [comment]
Thanks for contribution. I Haven't noticed this issue before
