### ISSUE TITLE
checkDirectory with create=TRUE

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#279]
@MarcinKosinski Are there some side effects of calling checkDirectory with create=TRUE?
Right now it should have no effect, yet this combination is called for example in createLocalRepo()

**Comment by MarcinKosinski** [comment]
I've No idea :p would You like to change this somehow? 

Marcin Kosinski

Dnia 11.07.2016 o godz. 19:25 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
Ok, so I will check if the checkDirectory(create=TRUE) is just a relict
from the past and if so then I will remove it

2016-07-12 9:30 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> I've No idea :p would You like to change this somehow?
>
> Marcin Kosinski
>
> Dnia 11.07.2016 o godz. 19:25 Przemysław Biecek <notifications@github.com>
> napisał(a):
>
> > @MarcinKosinski Are there some side effects of calling checkDirectory
> with create=TRUE?
> > Right now it should have no effect, yet this combination is called for
> example in createLocalRepo()
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pbiecek/archivist/issues/279#issuecomment-231960325>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEaPvtFB8K86t8uPONCt9SWHR76mlksuks5qU0KtgaJpZM4JJl5P>
> .
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Ok I get it, so `create=TRUE` was a special argument for `createLocalRepo` function.
It was checking whether the directory is a correct string and then it was creating repository.
In other cases (in other functions than createLocalRepo) we were onlcy checking whether the directory is a correct string and whether the repository exists.

I haven't check what changes did you make in `checkDirectory` but it looks like now createLocalRepo will not create an empty repository.

**Comment by MarcinKosinski** [comment]
Ok I get this now.

checkDirectory( create = TRUE) is used only in createLocalRepo and it does nothing when repoDir is passed but when repoDir is NULL then it uses globally set repoDir :P

**Comment by pbiecek** [comment]
ok, it look like repoDir cannot be NULL due to checks in stopifnot. Checking what will happen if I remove it
