### ISSUE TITLE
clean up - demo folder

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#285]
Isn't this a copy of `scripts` folder?

**Comment by pbiecek** [comment]
only files replicationScript*
shiny and list of packages are not in /demo/

And since demo is accessible through demo() so maybe it's better to remove replicationScript* from scripts

**Comment by MarcinKosinski** [comment]
I don't think someone is using `demo()` in the era of markdown-based github pages with full tutorials, blog posts on R-bloggers and fully documented manual pages :) I was about to delete demo, but it is not so necessary.
