### ISSUE TITLE
Extend webpage Posts section with: Blog about version 2.1.0 

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#290]
With examples for ahistory and links to useR materials

**Comment by pbiecek** [comment]
Materials:
https://rawgit.com/pbiecek/archivist/master/scripts/ahistrory_and_terrorism.html

https://rawgit.com/pbiecek/archivist/master/presentations/useR2016.html

https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016/How-to-use-the-archivist-package-to-boost-reproducibility-of-your-research

**Comment by MarcinKosinski** [comment]
I think we could use this link https://www.r-bloggers.com/a-link-that-can-tell-more-than-dozens-of-lines-of-r-code-whats-new-in-archivist/
to extend

https://github.com/pbiecek/archivist/blob/gh-pages/Posts.md
