### ISSUE TITLE
[Question] update on an existing artifact?

### ISSUE THREAD

**Issue by happyshows** [pbiecek/archivist#295]
Hi,

After reviewing a couple of artifacts and found one of them that requires a minor edit (let's say grammer fix). Is it possible to aread(), modify and write it back with the same md5 code?

**Comment by pbiecek** [comment]
The md5 hash is a unique function,
it can be used as a 'proof' that the downloaded artifact is the original one and is unchanged.

So technically it is possible to manually override the artifact with a given hash but it is not supported by archivist and is not recommended.

**Comment by happyshows** [comment]
ok thanks.
