### ISSUE TITLE
Rebuild staticdocs/pkgdown after cran publication of 2.1.1

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#301]
http://pbiecek.github.io/archivist/staticdocs/

**Comment by MarcinKosinski** [comment]
I think the whole website could be `pkgdown`

**Comment by pbiecek** [comment]
In few days I am going to upload new version of archivist to CRAN
(along with pdf of the jss article),
@MarcinKosinski do you plan to convert the website to pkgdown in close future?

**Comment by MarcinKosinski** [comment]
I can create `pkgdown` and push it to gh-pages branch to `staticdos` folder or some similiar - http://pbiecek.github.io/archivist/staticdocs/
Our website is way more complex than `pkgdown` http://pbiecek.github.io/archivist/ but I think we can reduce it to `pkgdown` as this is convenient way to publish pkg website

**Comment by MarcinKosinski** [comment]
@pbiecek can you point to the new source of our website?

Settings -> GitHub Pages -> Source -> `docs/` directory - I am not the owner of the repository and I can not do this. 

After this please close the issue.

**Comment by pbiecek** [comment]
done
