### ISSUE TITLE
Overlapping sections in http://pbiecek.github.io/archivist/

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#315]
Images with the architecture overview are too wide and are currently overlapping with right panel

<img width="1263" alt="screen shot 2017-05-01 at 22 40 50" src="https://cloud.githubusercontent.com/assets/4624318/25594144/b86f6f00-2ebf-11e7-8420-bff7427ccdea.png">

**Comment by MarcinKosinski** [comment]
This html is generated from README that is written in markdown. I have no idea whether one can specify width and height fot the image while including this image into markdown file.

PS. I didn't got notification about this issue. I am not mentioned nor assigned, and I think we do not have the Notifications launched in the Settings.

**Comment by MarcinKosinski** [comment]
![image](https://user-images.githubusercontent.com/6773454/33075218-0bc1b2b8-cec9-11e7-8dca-e7fff182375f.png)


fixed with the today's commit https://github.com/pbiecek/archivist/commit/5b2cf435f59565b333ae20ef19ca8e0b42f6d5f7

Perhaps by an accident

**Comment by pbiecek** [comment]
it was not an accident
