### ISSUE TITLE
createLocalRepo in an existing archivist repo

### ISSUE THREAD

**Issue by wiedemak** [pbiecek/archivist#318]
Is there any reason why createLocalRepo(R) does not check for an existing archivist repository? 
If it is done twice for some reason, backpack.db is reinitalized and summary/showLocalRepo() return the repository is emtpy.  The *.rda files still exist but can't be loaded anymore.

**Comment by pbiecek** [comment]
Thanks, this should be checked.
Will be fixed

**Comment by pbiecek** [comment]
fixed with 03323a9
