### ISSUE TITLE
asearchLocal uses archivist::aoptions("repoDir") even when the repo input argument is provided 

### ISSUE THREAD

**Issue by harell** [pbiecek/archivist#333]

**Comment by harell** [comment]
asearchLocal uses archivist::aoptions("repoDir") even when the repo input argument is provided.

The problem manifests itself when there is more than one database, and aoptions("repoDir") points differently than the repo input argument.

**Comment by pbiecek** [comment]
Thanks, would you check if df1ba84  solves this problem?

**Comment by harell** [comment]
Solved. Thanks
