### ISSUE TITLE
Is ascii = TRUE needed in saveToRepo function?

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#59]
I've noticed that `saveToRepo()` function creates a much bigger file than regular default `save()`  when saving an artifact. For example when I regularly load an object from a file that had 13 MB and save it with `saveToRepo()` it shows up that the file now has almost 89 MB.

````{Ruby}
> load("D:/Museum/analizaMarcin.rda")
> library(archivist)
> saveToRepo(analiza, getwd())
[1] "7c3b57cb4f57016493539c221ea50baf"
> file.info("gallery/7c3b57cb4f57016493539c221ea50baf")$size
[1] NA
> file.info("gallery/7c3b57cb4f57016493539c221ea50baf.rda")$size
[1] 88235933
> file.info("D:/Museum/analizaMarcin.rda")$size
[1] 13739958
````

I think this is the matter of `ascii=TRUE` parameter in `save()` function (which is used in saveToRepo()`.

> save(analiza, file="test.rda", ascii = TRUE)
> file.info("test.rda")$size
[1] 88235933
````


Is that parameter really necessary?

**Comment by MarcinKosinski** [comment]
I've added the `ascii` parameter (default `ascii = TRUE`) to  the `saveToRepo()` function.
Also added this to `extract.data` function. There is a note about this in `saveToRepo()` manual.

**Comment by pbiecek** [comment]
in archivist2 I've added compress = "bz", compression_level = 9 to reduce file size further.
fortunately it does not matter for load() so same repositories can be accessed by both versions
