### ISSUE TITLE
Version 1,3

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#62]
Are we planning to release version 1.3 on cran?
With new setLocal/setGithub functions and few fixed bugs and added ascii=TRUE parameter to saveToRepo funciton and added functionality enabling deleting many objects in 1 query in rmFromRepo?

**Comment by pbiecek** [comment]
Sure,
shall we have any additional features released with 1.3?

**Comment by MarcinKosinski** [comment]
I think this may be enough for version 1.3

**Comment by MarcinKosinski** [comment]
Will it be ok if I'll upload new version?

**Comment by pbiecek** [comment]
New uploads needs to be mail confirmed by the maintainer, so I do not think you can alone.
I will upload it tomorrow.

**Comment by MarcinKosinski** [comment]
Ok, good to know.

**Comment by pbiecek** [comment]
on CRAN
