### ISSUE TITLE
Problem with numerical precision

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#68]
No idea why, but sometimes objects are restored with slightly different values. 
The difference is in the range of numerical precision, but then the new object has a new and different md5 hash.

a <- seq(0,1,0.1)
saveToRepo(a)
b <- aread("pbiecek/graphGallery/77fb759a5406ceac4643614c4a7e057b")
a-b

 [1] 0.000000e+00 0.000000e+00 0.000000e+00 5.551115e-17 0.000000e+00 0.000000e+00 0.000000e+00
 [8] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00

**Comment by pbiecek** [comment]
Ok, the problem is that saveToRepo with default ascii = TRUE stores numbers in decimal format.
What about using ascii = FALSE by default?

**Comment by pbiecek** [comment]
I've changed ascii = FALSE in all files. 
With ascii = TRUE there were very strange errors. 
BTW: we need unit tests

**Comment by MarcinKosinski** [comment]
Also ascii = FALSE makes that stored objects are smaller.This is a good solution
