### ISSUE TITLE
onLoad or onAttach?

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#69]
What about moving 
  assign( x = "sqlite", value = dbDriver( "SQLite" ), envir = .ArchivistEnv )
  assign( x = ".GithubURL", value = "https://raw.githubusercontent.com/", envir = .ArchivistEnv )

to onLoad() function instead of onAttach()?

Then one may call 
archivist::aread("pbiecek/graphGallery/2a6e492cb6982f230e48cf46023e2e4f")

without library(archivist)

Currently it breaks because .GithubURL is not visible.

**Comment by MarcinKosinski** [comment]
Ok. That's a good solution
