### ISSUE TITLE
Annoying behavior of %a% operator

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#70]
When one works with a `data.frame` and pipes it several times in several analyses and uses `%a%` operator it produces a warning from `saveToRepo` function that remindes one have already archived this artifact. It is funny when we even use it in one pipe but with `lm` function from which we extracts data. It's rather annoying and maybe it could be disabled globally in a function like `archivistOptions(warnings=FALSE)`

````{Ruby}
> createEmptyRepo("example")
Directory example did not exist. Forced to create a new directory.
> setLocalRepo("example")
> 
> iris %a%
+    filter(Sepal.Length > 2) %a%
+    lm(Petal.Width ~.,data=.)

Call:
lm(formula = Petal.Width ~ ., data = `__LHS`)

Coefficients:
      (Intercept)       Sepal.Length        Sepal.Width  
         -0.47314           -0.09293            0.24220  
     Petal.Length  Speciesversicolor   Speciesvirginica  
          0.24220            0.64811            1.04637  

Warning message:
In saveToRepo(env[[nm]], archiveData = FALSE, userTags = paste0("name:",  :
  This artifact's data was already archived. Another archivisation executed with success.
> 
> library(ggplot2)
Need help? Try the ggplot2 mailing list: http://groups.google.com/group/ggplot2.
> iris %a%
+    ggplot(aes(Sepal.Length,Petal.Width)) +
+    geom_point()
Error: No layers in plot
In addition: Warning message:
In saveToRepo(env[[nm]], archiveData = FALSE, userTags = paste0("name:",  :
  This artifact's data was already archived. Another archivisation executed with success.
````

**Comment by pbiecek** [comment]
So what about setting warnings=FALSE by default?
(not only for %a% but for all calls to saveToRepo())

**Comment by MarcinKosinski** [comment]
How would you then set it up to warnings=TRUE in `%a%`if there's such desire? It's rather a matter of an extra parameter for this: `%a%` function.

**Comment by pbiecek** [comment]
I meant, setting it through global archivistOptions() with default to FALSE.

Since %a% is working as operator it should not have more than two arguments

Other solution: two operators like
%A% and %a% while the %A% have warnings=TRUE while %a% uses FALSE


2015-07-21 12:34 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> How would you then set it up to warnings=TRUE in %a%if there's such
> desire? It's rather a matter of an extra parameter for this: %a% function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/70#issuecomment-123258091>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
2 operator would be to much.

> I meant, setting it through global archivistOptions() with default to FALSE

This solution sounds good to me.

**Comment by pbiecek** [comment]
Works with getArchivistOptions("silent"),
I think that default repo may be set in similar way
uniform and easy

2015-07-21 14:39 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> 2 operator would be to much.
>
> I meant, setting it through global archivistOptions() with default to FALSE
>
> This solution sounds good to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/70#issuecomment-123292276>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
`aOptions` name would more match with new archivist convention of names :)

**Comment by pbiecek** [comment]
for both set and get?
or with overloaded `aOptions<-`?

2015-07-21 18:01 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> aOptions name would more match with new archivist convention of names :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/70#issuecomment-123385346>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
get: aOptions("warnings")
set: aOptions("warnings") <- "silent"
`warnings` would be default parameter

**Comment by pbiecek** [comment]
ok, just two but's

aOptions("silent") <- TRUE
(since silent is an argument of saveToRepo)

and since we have aread and ahistory, then it should be aoptions
(lowercase, but does not look that good)


2015-07-21 19:06 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> get: aOptions("warnings")
> set: aOptions("warnings") <- "silent"
> warnings would be default parameter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/70#issuecomment-123404626>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Yes it looks better. Couldn't Have think about something simpler :)

Marcin Kosinski

Dnia 21 lip 2015 o godz. 19:12 pbiecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
it turns out that we cannot use aoptions<- function
since it's side effect is an override of some object in global namespace
e.g. aoptions(silent) <- TRUE will change variable silent in global namespace.

Going to use
aoptions(v, k)
and if k = NULL then it will work as get otherwise as set function

**Comment by MarcinKosinski** [comment]
Maybe we should keep this `silent` vairable in an archivist's environment
.ArchEnv?

2015-07-21 21:04 GMT+02:00 pbiecek <notifications@github.com>:

**Comment by pbiecek** [comment]
It is there


Dnia 22 lip 2015 o godz. 10:36 Marcin Kosiński <notifications@github.com> napisał(a):
