### ISSUE TITLE
More aoptions in archivist 1.6

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#72]
Right now we have two mechanisms for setting default values.
aoptions for silent and setLocalRepo for repositories.
This may be simplified, we can use aoptions for most archivist arguments.

**Comment by MarcinKosinski** [comment]
hmmm so maybe let's use `aoptions(repoDir="directory")`  as a wrapper over `setLocalRepo` function :)

**Comment by MarcinKosinski** [comment]
So now maybe in ver 1.7?

**Comment by pbiecek** [comment]
cone with #029346f920

**Comment by pbiecek** [comment]
029346f920
