### ISSUE TITLE
CRAN Task View: Reproducible Research

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#73]
Shouldn't we propose `archivist` package to join [`CRAN Task View: Reproducible Research`](https://cran.r-project.org/web/views/ReproducibleResearch.html)

**Comment by pbiecek** [comment]
Good idea, going to email Max Kuhn about this

**Comment by MarcinKosinski** [comment]
Did they even response?

**Comment by pbiecek** [comment]
Yes:
Thanks. I’ll check it out.

**Comment by MarcinKosinski** [comment]
Probably holidays lengthened the time :)
Maybe a little reminder with article about `archivist` in JSS would help after it's publication (if they'll publicate it).

**Comment by pbiecek** [comment]
Publication process in JSS takes on average more than one year. 
So I am going to send the reminder sooner.

**Comment by pbiecek** [comment]
I've resend reminder

**Comment by pbiecek** [comment]
At least done with https://cran.r-project.org/web/views/ReproducibleResearch.html

**Comment by MarcinKosinski** [comment]
Great !
