### ISSUE TITLE
pin/addHooksToPrint function - overloading print

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#74]
Maybe we should think about something similar with the usage of *archivist*
[Embedding RData files in R Markdown files for more reproducible analyses](http://rmarkdown.rstudio.com/articles_rdata.html)

**Comment by pbiecek** [comment]
Definitely,
I think that we need three new complementary functionalities:
1.	support for git in the read mode (for private repositories, this will require authorization)
2.	support for git+github in the write mode (this will give automated commits)
3.	automated archivisation of objects in Rmarkdown/knitr scripts. But this requires point 2.

**Comment by MarcinKosinski** [comment]
Let's make it epic functionalities :)

I was also thinking about making a graph of the analysis pipeline with the
usage of forcenetwork from networkD3 package. I'll try to write something
about that in this or next week.

2015-08-16 21:20 GMT+02:00 pbiecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
Something similar? 
http://www.rpubs.com/ramnathv/including_rmd_source

[Source](https://www.facebook.com/groups/uzytkownicyR/permalink/529910007157768/)

**Comment by pbiecek** [comment]
It's about saving Rmd file as well
We are focused on R objects, sot the Rmd file needs to be read as character vector.

But for large number of objects, or for large objects it would be better to store them apart from html.
Will try this after holidays

**Comment by MarcinKosinski** [comment]
Do we still consider this functionality as doable or needable :)?

**Comment by pbiecek** [comment]
Integration of Rmd and archivist is doable and I think we need it.
I do not think that we have to embed binary artifacts in md/html file,
rather to add an repository in the same directory that Rmd/md/html is located.

**Comment by pbiecek** [comment]
What do you think about this solution:

1. add a function `pin` to the archivist. It works within Rmd reports. First it checks if there is any default repository, if not it creates one with name `archivist`
2. then the function `pin` calls the `saveToRepo` and stores the artifact in the repository
3. then it creates small badge in the md/html report that link to file ./archivist/gallery/md5_hash.rda
In the final report it will be enough to click this link to download the artifact.

**Comment by MarcinKosinski** [comment]
Looks good.

Should a user directly use the `pin` function or it will be an automated
proces?

2015-10-25 15:17 GMT+01:00 pbiecek <notifications@github.com>:

**Comment by pbiecek** [comment]
It's easier to assume that 'pin' is called directly.

**Comment by MarcinKosinski** [comment]
@pbiecek  Maybe you could use `alink` and `archive` function to create `pin` somehow? 
`alink` returns links in `markdown`, `latex` and `raw` format so 

````{R}
alink(archive(iris))
# or
archive(iris, alink = TRUE)
````

will archive artifact on GitHub and will return a link to this artifact to download this object from GitHub.

**Comment by MarcinKosinski** [comment]
TODO: useCase for alink (done in local repo)

**Comment by pbiecek** [comment]
I was using alink here:
file:///Users/pbiecek/GitHub/PieczaraPietraszki/UniwersytetDzieci/prezentacja.html

quite happy with this solution.
I can describe it shortly as a use case

**Comment by pbiecek** [comment]
a wrapper over alink is added
now it links all objects of given class

see here:
https://rawgit.com/BetaAndBit/PieczaraPietraszki/master/UniwersytetDzieci/prezentacja.html
for an example

**Comment by MarcinKosinski** [comment]
Looks great!

I am not fully convinced to the function name where `archivist` is written as `Archivist`. Maybe it could be named `addHooksToPrint` ? I am wondering whether we need `Github/Remote` version of `addHooks`, where `archive( alink = TRUE, ...) [... -> further params to alink]` could be used, since hooks to remote `Repository` are added so I assume the artifacts will be send to Remote/Github anyway.

In `saveToRepo()` function there is `value` parameter which, when set to `TRUE`, returns archived artifact. This parameter could be added to `archive` in a similar form. Then one could use

````{R}
archive(artifact, alink = TRUE, value = TRUE, ...) 
````

but this is still longer notation than regular artifact name (after addHooks has been called).



**Offtopic**: Have you considered ggplot repel to avoid overlapping text-annotations in ggplots?
http://www.r-bloggers.com/repel-overlapping-text-labels-in-ggplot2/

**Comment by pbiecek** [comment]
Good idea, I've change it to addHooksToPrint.

I think that `archive` can be used instead of` saveToRepo()`. But I've just not familiar enough with this function (yet).
But this will change.

`ggrepel` is good idea. Thanks

**Comment by pbiecek** [comment]
It turns out that here ggrepel is not that good. But will use it in other usecase.

**Comment by MarcinKosinski** [comment]
Is there a Local version of `pin/addHooksToPrint` that'll add hooks to Local `Repository` matched with outputed file?

**Comment by pbiecek** [comment]
Not yet. Do you think it will be useful? 
I do not know how to link aread() with local repo that is at unknown location.

**Comment by MarcinKosinski** [comment]
No idea. But I thought this was the main goal, not the Remote support :)
But if that's it, then you might considering closing this issue and provide
a use case for https://github.com/pbiecek/archivist/issues/192

2016-02-02 0:42 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
So, maybe for local repo we will embed links to files [`a href`] but without calls of `aread`

**Comment by MarcinKosinski** [comment]
Sounds good. Then the gallery should somehow always be added to the html
object when being shared with other collaborators

2016-02-05 0:39 GMT+01:00 Przemysław Biecek <notifications@github.com>:
