### ISSUE TITLE
update NEWS file before 2.1.0 publication

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#75]
This package is still and probably will for long be under development.
I think it's time to add a NEWS file, in which we'll write what happened
between `archivist` releases.

**Comment by pbiecek** [comment]
Done,
I've updated the 1.6 release, 
will do previous version in 'free time' 
(if you know about important milestones, please add them)

**Comment by MarcinKosinski** [comment]
Ok

Marcin Kosinski

Dnia 27 sie 2015 o godz. 18:04 pbiecek <notifications@github.com> napisał(a):

**Comment by MarcinKosinski** [comment]
There will be no more updates for ver 2.1.0
