### ISSUE TITLE
Dependencies in archivist

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#77]
So far archivist have 4 packages in `Depends` section.

-    `RSQLite`,
-   `DBI`,
-    `shiny`,
-    `lubridate`.

One can see that `RSQLite` has `DBI` package in dependencies [https://cran.r-project.org/web/packages/RSQLite/index.html](https://cran.r-project.org/web/packages/RSQLite/index.html) so we might remove `DBI` from `Depends` section. What is more, I think we only use one function from `lubridate` package - `now()`, so maybe we should change `@import lubridate` to `@importFrom lubridate now` in the `[archivist-package.R file](https://github.com/pbiecek/archivist/blob/master/R/archivist-package.R)`. Then archivist would only depend on `RSQLite` and `shiny`. Functions from `shiny` package are only used in `shinySearch...` function - so maybe we should move `shiny` from `Depends` to `Suggets` like it is done in `rvest` package for [`guess_encdoing`](https://github.com/hadley/rvest/blob/master/R/encoding.R) function where there is a sentence at the beginning of the function's declaration
````{Ruby}
guess_encoding <- function(x) {
  if (!requireNamespace("stringi", quietly = TRUE)) {
    stop("stringi package required for encoding operations")
  }
````

`guess_encdoing` function in somehow treated as an extra functionality to base functions from `rvest` package and there even is a sentence in this function's manual

>
> #' @section stringi:
> #'
> #' These function are wrappers around tools from the fantastic stringi
> #' package, so you'll need to make sure to have that installed.
>

so maybe we should treat `shinySearch...` also as an extra function and move it to the `Suggests` section.

Finally in the [`archivist-package.R` file](https://github.com/pbiecek/archivist/blob/master/R/archivist-package.R) there is specified

````{Ruby}
#' @import RCurl
#' @import httr
#' @import RSQLite
#' @import DBI
#' @import shiny
#' @import lubridate
#' @import digest
#' @importFrom utils head
#' @importFrom utils zip
#' @importFrom grDevices png
#' @importFrom grDevices dev.off
#' @importFrom graphics plot
#' @importFrom graphics par
#' @importFrom graphics barplot
#' @importFrom graphics par
````

I think that

- from `RCurl` we only use `getBinaryURL` function. Maybe should change to `@imporFrom RCurl getBinaryURL`.
- from `digest` we only use `digest` function. Maybe should change to `@imporFrom digest digest`.
- we do not have to import from `graphics` package as it is provided with `base` package. I suggest to remove `import From graphics *` lines
- the same with imports from `utils` and `grDevices` as for the `graphics`

Lastly:

- Dependencies on RSQLite:  might be replaced with (mostly used in [`createEmpyRepo()`](https://github.com/pbiecek/archivist/blob/master/R/createEmptyRepo.R) function and in `zzz.R` file)

- @importFrom RSQLite dbWriteTable
- @importFrom RSQLite dbGetQuery
- @importFrom RSQLite dbDisconnect
- @importFrom RSQLite dbConnect
- @importFrom RSQLite dbReadTable
- @importFrom RSQLite dbDriver

What's even funnier? Than all those functions come from `DBI` package. So maybe we should remove `RSQLite` from `DESCRIPTION` file and only move `DBI` to `Imports`.

When I first tried to organize Dependencies I wasn't so aware of package dependencies as I am today. What do you think about that?

**Comment by pbiecek** [comment]
Less dependencies sounds good.

**Comment by MarcinKosinski** [comment]
I may work on it on my own fork and then apply a pull request when it'll be ready and working.
I think it's a good time and situation to create some functions' tests or maybe `travis` is enough?

**Comment by MarcinKosinski** [comment]
So far so good - no dependencies :) Now we'll need some test to check whether whole package works properly as intended.

Here are changes [https://github.com/MarcinKosinski/archivist/commit/8a5178051a99350e5c026dfe4b0116eb1b3a1c3b](https://github.com/MarcinKosinski/archivist/commit/8a5178051a99350e5c026dfe4b0116eb1b3a1c3b)

````{Ruby}
> devtools::install_github("MarcinKosinski/archivist")
Downloading github repo MarcinKosinski/archivist@master
Installing archivist
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/Kamil/AppData/Local/Temp/RtmpQnhmEp/devtools16cc2ae43845/MarcinKosinski-archivist-8a51780"  \
  --library="C:/Users/Kamil/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'archivist' ...
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (archivist)
> library(archivist)
Welcome to the archivist (version: 1.6.1).
> 
````

**Comment by pbiecek** [comment]
demos may serve as tests
https://github.com/pbiecek/archivist/tree/master/demo

**Comment by MarcinKosinski** [comment]
I've added tests and removed dependencies. Archivist is now free of dependencies :)
Pull request and check results is here #79

**Comment by pbiecek** [comment]
Great. Can we close this issue?

**Comment by MarcinKosinski** [comment]
close #77

Marcin Kosinski

Dnia 10 wrz 2015 o godz. 20:44 pbiecek <notifications@github.com> napisał(a):
