### ISSUE TITLE
`tags` variable in shinySearch.. function

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#78]
Where do we specify `tags` parameter for this function?

[https://github.com/pbiecek/archivist/blob/master/R/shinySearchInLocalRepo.R#L52](https://github.com/pbiecek/archivist/blob/master/R/shinySearchInLocalRepo.R#L52)

**Comment by pbiecek** [comment]
tags in line 60 are HTML tags.
tags used for search are from textInput

**Comment by MarcinKosinski** [comment]
I am trying to move `shinySearchInRepo` function to mode that will only work after `shiny` package is loaded by user. I've changed regular functions to their `shiny::` equivalences but I have no idea what to do with those tags. I receive a warning when I don't load `shiny` package like this below. I am working on this version of function [https://github.com/MarcinKosinski/archivist/blob/8a5178051a99350e5c026dfe4b0116eb1b3a1c3b/R/shinySearchInLocalRepo.R](https://github.com/MarcinKosinski/archivist/blob/8a5178051a99350e5c026dfe4b0116eb1b3a1c3b/R/shinySearchInLocalRepo.R)

````{Ruby}
> devtools::install_github("MarcinKosinski/archivist")
Downloading github repo MarcinKosinski/archivist@master
Installing archivist
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/Kamil/AppData/Local/Temp/RtmpQnhmEp/devtools16cc2ae43845/MarcinKosinski-archivist-8a51780"  \
  --library="C:/Users/Kamil/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'archivist' ...
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (archivist)
> library(archivist)
Welcome to the archivist (version: 1.6.1).
> shinySearchInLocalRepo("asdads")
Error in tag("div", list(...)) : object 'tags' not found
> createEmptyRepo("aaaa")
Directory aaaa did not exist. Forced to create a new directory.
> shinySearchInLocalRepo("aaaa")
Error in tag("div", list(...)) : object 'tags' not found
> library(shiny)
Warning message:
> shinySearchInLocalRepo("aaaa")

Listening on http://0.0.0.0:7281
````

**Comment by MarcinKosinski** [comment]
Maybe I also should `requireNamespace` for `htmltools` package?

**Comment by MarcinKosinski** [comment]
It was exported by `shiny`'s package `NAMESPACE`.
