### ISSUE TITLE
ssl.verifypeer = FALSE in getBinaryURL

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#81]
Why do we have ssl.verifypeer = FALSE in getBinaryURL?
It crashes my R under OSX, with 
'Error in function (type, msg, asError = TRUE)  : 
  SSL: CA certificate set, but certificate verification is disabled'

It is working without this option.

**Comment by MarcinKosinski** [comment]
I don't remember. Most probable is that I've copied default setting from stackoverflow. If this will work also under windows then we can delete this option

**Comment by MarcinKosinski** [comment]
If tests have passed we can close this issue?

**Comment by pbiecek** [comment]
let it be
