### ISSUE TITLE
use file.path function instead of paste0

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#82]
In some places of the source code of the main functions in `archivist` we use `paste0` function to specify the directory to downloaded files or to the created `repositories`. To be more platform independent I think those parts of code should be rewritten with `file.path` function.

Example: [https://github.com/pbiecek/archivist/blob/master/R/createEmptyRepo.R#L131](https://github.com/pbiecek/archivist/blob/master/R/createEmptyRepo.R#L131)

**Comment by pbiecek** [comment]
Is it planned for 1.8 or 1.7?

**Comment by MarcinKosinski** [comment]
Next version after 1.7

I think maybe we should use 1.7.x format for further releases because in
such tempo
we'll achieve version 10.0 till December :)

2015-09-16 22:54 GMT+02:00 pbiecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
@wchodor has expressed a desire to fix this issue :)

**Comment by MarcinKosinski** [comment]
@wchodor Can you sum up your changes? Have you finished this issue :)?

**Comment by wchodor** [comment]
I have finally managed to replace `paste0` by `file.path` in all appropriate places. In addition, I have removed from `checkDirectory`'s body these parts which were unnecessary  after change of `paste0`.
All alterations can be seen in this commit:
https://github.com/wchodor/archivist/commit/b81ca932118d128c20c07d09d089a6497c0cf319

**Comment by MarcinKosinski** [comment]
Thanks. Close Closes

Marcin Kosinski

Dnia 25 lis 2015 o godz. 17:39 Witold Chodor <notifications@github.com> napisał(a):
