### ISSUE TITLE
Why archivist is depend on the Rcpp, jsonlite and mime packages?

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#84]
I thought `archivist` is now `DEPENDENCIES`-free. But during installation from github it seems that functions that are imported from other packages are dependent on other packages. We are dependent on `Rcpp`, `jsonlite` and `mime` - the problem is that `Rcpp` development has been moved from `CRAN` to RStudio's website. 

Do you think there is any possibility to be `Rcpp`-dependency free? There might be a problem with `Rcpp` normal installation.

````{R}
> devtools::install_github("pbiecek/archivist")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Rcpp’
> install.packages("Rcpp", repos='http://cran.us.r-project.org') 
Installing package into ‘C:/Users/Marcin/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://cran.us.r-project.org/bin/windows/contrib/3.2/Rcpp_0.12.1.zip'
Content type 'application/zip' length 3189570 bytes (3.0 MB)
downloaded 3.0 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Marcin\AppData\Local\Temp\RtmpSCBDT4\downloaded_packages
> devtools::install_github("pbiecek/archivist")
Downloading github repo pbiecek/archivist@master
Installing archivist
Installing 2 packages: jsonlite, mime
package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘mime’ successfully unpacked and MD5 sums checked
"D:/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/Marcin/AppData/Local/Temp/RtmpSCBDT4/devtools2148183c31c3/pbiecek-archivist-c2d0a55"  \
  --library="C:/Users/Marcin/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'archivist' ...
** R
** demo
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (archivist)
````

**Comment by pbiecek** [comment]
Do you know which of our imports is Rcpp dependent?
I could not find the dependency

**Comment by pbiecek** [comment]
Here is a nice tool for exploration of dependency tree
https://mran.revolutionanalytics.com/package/archivist/#depend

but I do not see Rcpp

**Comment by pbiecek** [comment]
Maybe the problem is that 'devtools' is Rcpp dependent?
And Rcpp had to be installed in order to use install_github?

**Comment by MarcinKosinski** [comment]
Yes it looks like it's caused by `devtools` package.
I've seen in many places that people replace such chunks:

````{R}

if (!require(devtools)) {
    install.packages("devtools")
    require(devtools)
}
install_github("pbiecek/archivist")

# as in our README.mr
````
with

````{R}

if (packageVersion("devtools") < 1.6) {
  install.packages("devtools")
}devtools::install_github("airoldilab/sgd")

````

So perhaps in versions older that 1.5 this problem is fixed?

About this graph of dependencies - it looks very interesting :) but in the
new version it'll be smaller.
About reverse dependencies of the archivist, there is one package SpaDES
https://mran.revolutionanalytics.com/package/SpaDES/#depend
I wonder why they needed archivist? Maybe it could be a nice idea for a
use-case


2015-09-14 23:37 GMT+02:00 pbiecek <notifications@github.com>:

**Comment by pbiecek** [comment]
The only place where I saw devtools is the replication script.
I removed devtools from this file so I guess now it's devtools/Rcpp free?

**Comment by MarcinKosinski** [comment]
Those packages are still downloaded when I install `archivist` from github but maybe it's necessary with `devtools`

**Comment by pbiecek** [comment]
I think it's related to devtools.

**Comment by MarcinKosinski** [comment]
won't fix
