### ISSUE TITLE
ahistory functionality in .Rmd files 

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#97]
I have changed a code of the `ahistory`  in this commit  to enable artifact's history formating in outputs of the render over  `.Rmd` files. #a68bcd5

Was this what we were looking for?
[https://htmlpreview.github.io/?https://github.com/pbiecek/archivist/blob/master/ghPage/Pedigree_Retrieval.html](https://htmlpreview.github.io/?https://github.com/pbiecek/archivist/blob/master/ghPage/Pedigree_Retrieval.html)

**Comment by pbiecek** [comment]
Looks great,
so now, let's add links to values in the md5hash column 
Since 'ahistory' may check where is the default repository (relative path) it can adds links to 
./Pedigree_Example/gallery/ff575c261c949d073b2895b05d1097c3.rda

**Comment by MarcinKosinski** [comment]
`ahistory` has it's print method now for `.Rmd` files. This issue can be closed as we have other one for `pin` function: https://github.com/pbiecek/archivist/issues/74

**Comment by MarcinKosinski** [comment]
@pbiecek `ahistory` now has a way to provide hooks to history table/kalbe
like in the end of this use case 
https://htmlpreview.github.io/?https://github.com/pbiecek/archivist/blob/master/ghPage/Pedigree_Retrieval.html

**Comment by pbiecek** [comment]
The functionality is cool,
but I have doubts related to the interface / list of arguments.
Like you need to set both repoDir, user and repo arguments. Looks complicated.
Working on repo class.

**Comment by MarcinKosinski** [comment]
Yes it does and I think requires separate issue 

Marcin Kosinski

Dnia 26.01.2016 o godz. 21:05 Przemysław Biecek <notifications@github.com> napisał(a):
